### ISSUE TITLE
add new token to Bert

### ISSUE THREAD

**Issue by ReySadeghi** [huggingface/transformers#11241] opened 2021-04-14 04:48 UTC
Hi,
I want to fine-tune Bert on tweets and I want to add some new tokens. I tried following code but it may have problem because after adding tokens and during reading sentences and tokenizing, it has lag and couldn't pass it.
any idea please? 

I tried this:
tokenizer.add_tokens(["NEW_TOKEN"])
model.resize_token_embeddings(len(tokenizer))

**Comment by LysandreJik** [comment] 2021-04-14 14:40
Could you provide a reproducible code example alongside the error that happened?

**Comment by ReySadeghi** [comment] 2021-04-14 15:50
my code is:
................................................................
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased",max_len=256)
vocab=[]
with open('vocab30k.txt', mode='r',encoding="utf8",errors='ignore') as file2:
   for line2 in file2:
     line2=line2.split('\n')[0]
     vocab.append(line2)

tokenizer.add_tokens(vocab)
model= BertForMaskedLM.from_pretrained("bert-base-uncased")
model.resize_token_embeddings(len(tokenizer)) 

dataset = LineByLineTextDataset(
    tokenizer=tokenizer,
    file_path="fa5M_shuffeled.txt",
    block_size=128,
)


data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer, mlm=True, mlm_probability=0.15
)


training_args = TrainingArguments(
    output_dir="fineTunedModel/",
    overwrite_output_dir=True,
    num_train_epochs=1,
    per_gpu_train_batch_size=16,
    save_steps=10_000,
    save_total_limit=2,
    prediction_loss_only=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=dataset,
)

trainer.train()

....................................................
when I don't add_token, every thing is ok and training start but when I use add_token to add my new vocab, my code is still running and doesn't pass to go to start training , and nothing happen.

**Comment by LysandreJik** [comment] 2021-04-14 20:50
This is probably because it takes a very long time to add all tokens. Could you install from source:
`pip install -U git+https://github.com/huggingface/transformers` and let me know if it fixes the issue? We recently merged a PR that should speed this up dramatically.

**Comment by ReySadeghi** [comment] 2021-04-15 11:58
I installed via your link and try to add 5000 new vocab and it works.
thanks so much.
another question is ,
what is the limitation of number of tokens that we want to add? I want to add 30k new token.

**Comment by n1t0** [comment] 2021-04-15 20:03
1. It depends on the size of the tokens. Adding tokens to the tokenizer this way is not scalable, and should only be used to handle a very limited number of tokens. Under the hood, it actually uses some Regex to extract these tokens, and there is a limitation in the size of the regex we can create.
2. Special tokens can be removed when decoding

**Comment by ReySadeghi** [comment] 2021-04-26 09:09
Hi, in term of adding token, I tried to add 10k new token to my BERT model tokenizer and I saved the tokenizer with "add_token.json" file.
So when I want to use the tokenizer I got this error:

AssertionError: Non-consecutive added token '#سلام' found. Should have index 100005 but has index 100006 in saved vocabulary.

any help?

**Closed** 2021-05-30 15:08 UTC
