### ISSUE TITLE
Could you support albert?

### ISSUE THREAD

**Issue by zhu1090093659** [huggingface/transformers#1777] opened 2019-11-09 14:38 UTC
## ❓ Questions & Help

For many students,who haven't large GPU,so they will use small model(eg albert),hence I hope you will support loading albert, Tkanks so much!

**Comment by julien-c** [comment] 2019-11-09 16:09
Duplicate of #1649 #1420 #1522 #1564 🤣🤣

**Closed by julien-c** 2019-11-09 16:09 UTC
