### ISSUE TITLE
Transformers 4.39.0 has breaking change on torch compatibility.

### ISSUE THREAD

**Issue by xkszltl** [huggingface/transformers#29895] opened 2024-03-27 07:56 UTC
### System Info

torch 1.13 + transformers 4.39.0

### Description

`torch.optim.LRScheduler` was only exposed in torch 2:
- https://github.com/pytorch/pytorch/pull/88503

Previously it was called `_LRScheduler` in torch 1.

This recent PR included in 4.39.0 imports it and lead to a hard requirement on torch 2:
- https://github.com/huggingface/transformers/pull/29588

FYI @younesbelkada 

This issue is captured by our CI where we have dependency on torch 1.

### Expected behavior

Suggest to check on version or API availability before use.
Given it's only a visibility change, a transparent fallback/re-route would be ideal.

**Comment by ArthurZucker** [comment] 2024-03-27 14:56
This is a duplicate of #29847, I'll push something asap and do a patch release. FYI @LysandreJik and @amyeroberts

**Closed** 2024-03-28 09:54 UTC
