### ISSUE TITLE
BART(base) - Finetune Is this a bug ? Or I am doing something wrong?

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [huggingface/transformers#5237] opened 2020-06-24 09:47 UTC
## I have finetuned my dataset using latest piece of code from master, by cloning and the building. 

Now when I try to load my finetuned model as shown in the examples of "summarization" (previous commit).

`from transformers import BartTokenizer, BartForConditionalGeneration, BartConfig
model = BartForConditionalGeneration.from_pretrained('FinetuneOutput/best_tfmr')
tokenizer = BartTokenizer.from_pretrained('FinetuneOutput/best_tfmr')`

I got the following error : 

`TypeError: special token mask_token has to be either str or AddedTokenFast but got: <class 'dict'>`

Am I missing something, or it is a BUG again ?

**Comment by thomwolf** [comment] 2020-06-24 10:13
Can you post the full error message?

**Comment by ShoubhikBanerjee** [comment] 2020-06-24 10:14
Are you asking for this or more??

`/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils.py in __init__(self, **kwargs)
    511                 else:
    512                     raise TypeError(
--> 513                         "special token {} has to be either str or AddedTokenFast but got: {}".format(key, type(value))
    514                     )
    515 

TypeError: special token mask_token has to be either str or AddedTokenFast but got: <class 'dict'>`

**Comment by thomwolf** [comment] 2020-06-24 10:23
I can't reproduce this on master.

Can you work with a stable release version or do you need features that are on master only?

**Comment by ShoubhikBanerjee** [comment] 2020-06-24 10:26
I am working from your master branch. 

After commit no #5227 ,  its not working, previously it was working fine.

**Comment by thomwolf** [comment] 2020-06-24 11:33
Ok, we are ficing some issues related to tokenizer serialization here: https://github.com/huggingface/transformers/pull/5056

Maybe it will so e your problem as well. Should be merged pretty soon.

**Comment by ShoubhikBanerjee** [comment] 2020-06-24 11:42
Thanx a lot Sir.

After "factory resetting" colab, and build the project from the source again, solved the issue.

I am really sorry for the inconvenience and appreciate the time you gave me. 

Thank a lot. From next time on wards I will keep in mind to "factory reset" colab.  :)

**Closed** 2020-06-24 11:42 UTC
