### ISSUE TITLE
Fine-tuning BertAbs on new dataset?

### ISSUE THREAD

**Issue by ehsan-soe** [huggingface/transformers#2374] opened 2019-12-31 03:09 UTC
## 🚀 Feature

Hi,
I wonder if there can be a script for fine-tuning BertAbs on new dataset?
Or if you have some hint to provide about this task? Not sure how to access loss from ```modeling_bertabs.py```.

Thanks

**Comment by sshleifer** [comment] 2020-03-03 15:36
duplicate of #2597, no update yet sadly.

**Closed by sshleifer** 2020-03-03 15:36 UTC
Labels: wontfix
