### ISSUE TITLE
no_speech_probablity

### ISSUE THREAD

**Issue by rizwanishaq** [huggingface/transformers#30777] opened 2024-05-13 13:46 UTC
The `pipeline` is designed to be a high-level wrapper that goes from audio inputs -> text outputs. Anytime we want something more granular than that, it's best to use the `model` + `processor` API:
```python
from transformers import WhisperProcessor, WhisperForConditionalGeneration
from datasets import load_dataset
import torch

model = WhisperForConditionalGeneration.from_pretrained("openai/whisper-tiny")
processor = WhisperProcessor.from_pretrained("openai/whisper-tiny")

librispeech_dummy = load_dataset("hf-internal-testing/librispeech_asr_dummy", "clean", split="validation")
sample = librispeech_dummy[0]["audio"]

input_features = processor(sample["array"], sampling_rate=sample["sampling_rate"], return_tensors="pt").input_features

outputs = model.generate(
    input_features, output_scores=True, return_dict_in_generate=True, max_new_tokens=128
)

transition_scores = model.compute_transition_scores(
    outputs.sequences, outputs.scores, normalize_logits=True
)

pred_text = processor.batch_decode(outputs.sequences, skip_special_tokens=True)
pred_language = processor.batch_decode(outputs.sequences[:, 1:2], skip_special_tokens=False)
lang_prob = torch.exp(transition_scores[:, 0])

print(pred_text)
print(pred_language)
print(lang_prob)
```
**Print Output:**
```
[' Mr. Quilter is the apostle of the middle classes and we are glad to welcome his gospel.']
['<|en|>']
tensor([1.])
```

_Originally posted by @sanchit-gandhi in https://github.com/huggingface/transformers/issues/25138#issuecomment-1836554598_

How we can get the no_speech_probablity with this code?

**Comment by amyeroberts** [comment] 2024-05-13 14:01
cc @sanchit-gandhi @ylacombe @kashif

**Comment by ylacombe** [comment] 2024-05-13 15:44
Hey @rizwanishaq, you can simply add the[ `no_speech_threshold` argument](https://huggingface.co/docs/transformers/model_doc/whisper#transformers.WhisperForConditionalGeneration.generate.no_speech_threshold) to the generate method:


```python
outputs = model.generate(
    input_features, output_scores=True, return_dict_in_generate=True, max_new_tokens=128, no_speech_threshold=0.2
)
```

Let me know if that works!

**Comment by ylacombe** [comment] 2024-05-13 16:23
Then it's related to a shortcoming of our Whisper implementation that we hope to fix soon: [we're not applying some of the features used for long-form generation to short audios](https://github.com/huggingface/transformers/issues/29508#issuecomment-2029435220).

We should be resolving this issue quite soon, I'll keep you up-to-date

**Comment by ylacombe** [comment] 2024-05-13 16:27
This is a duplicate of #29595, I'll close this issue, let's talk in #29595 if you have further questions!

**Closed by ylacombe** 2024-05-13 16:27 UTC
Labels: Audio

**Comment by ylacombe** [comment] 2024-09-17 08:51
For reference, it was fixed by https://github.com/huggingface/transformers/issues/29508!
Also see [this comment ](https://github.com/huggingface/transformers/issues/29595#issuecomment-2354923459)
