### ISSUE TITLE
Gemma optimizations for finetuning and infernece

### ISSUE THREAD

**Issue by rombodawg** [huggingface/transformers#29616] opened 2024-03-12 16:58 UTC
### System Info

Latest transformers version, most platforms. 

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Finetuning, inference

### Expected behavior

Recently it was discovered that poor optimization in transformers has been taken place, and there are ways to fix it. Bellow is a link on the findings
https://www.reddit.com/r/LocalLLaMA/comments/1bd18y8/gemma_finetuning_should_be_much_better_now/

**Comment by phanxuanphucnd** [comment] 2024-03-13 09:06
When i run with transformers==4.36.2 for LLama2, Mistral => Inference very ok
But, when run with upgrade version (4.38.2) => Very slow

Please check issues

**Comment by amyeroberts** [comment] 2024-03-13 10:30
Hi @phanxuanphucnd, could you open a new issue? This helps us keep better track of what has been resolved and addressed. The original issue post is a feature request, whereas you appear to be reporting a possible bug or regression

In the issue, can you make sure to include: 
* a minimal code snippet to reproduce the issue, or specifically the benchmarking 
* Information about the issue, in this case numbers about the running times between the two versions

**Comment by phanxuanphucnd** [comment] 2024-03-14 02:38
> Hi @phanxuanphucnd I meet the same problem. Has it been resolved? Thanks!

Down version transformers back to 4.36.2. :<

**Comment by danielhanchen** [comment] 2024-03-16 08:15
@phanxuanphucnd Wait are you saying Llama and Mistral themselves are slower now? That's very interesting - the Gemma bug fixes I did do make finetuning itself somewhat slower, but the results become accurate. I would say 5% at maximum. I also fixed the Llama RoPE issue, so another 5% hit.

However, for inference, recently the smart HF team made inference fully compile-able with `torch.compile`, enabling 4x faster inference - this might cause non compiled codepaths to be slower.

However, to my knowledge, Mistral itself was not touched, nor did I include changes to update Mistral - this leads me to suggest some other issue is causing the slowdown.

So from the back of the envelope (ie just guess) how much % slower is Mistral, Llama and or Gemma?

**Comment by phanxuanphucnd** [comment] 2024-03-25 19:23
> @phanxuanphucnd Wait are you saying Llama and Mistral themselves are slower now? That's very interesting - the Gemma bug fixes I did do make finetuning itself somewhat slower, but the results become accurate. I would say 5% at maximum. I also fixed the Llama RoPE issue, so another 5% hit.
> 
> However, for inference, recently the smart HF team made inference fully compile-able with `torch.compile`, enabling 4x faster inference - this might cause non compiled codepaths to be slower.
> 
> However, to my knowledge, Mistral itself was not touched, nor did I include changes to update Mistral - this leads me to suggest some other issue is causing the slowdown.
> 
> So from the back of the envelope (ie just guess) how much % slower is Mistral, Llama and or Gemma?

Hi @danielhanchen 

When I refined the Vistral base model: `Viet-Mistral/Vistral-7B-Chat` and obtained the model at this repo id: `phucpx247/misa-vistral-7b-chat-lora-4ep-lr5e5-r32-alpha16-9k1`. During inference with version 4.38.2 transformers it is x4 times slower.

If Mistral is published on hugging face, I tried it and it did not have the above problem.

Is it because of the SFT process? But I don't think it's because of the training process. I refer from Github: https://github.com/hiyouga/LLaMA-Factory

**Comment by phanxuanphucnd** [comment] 2024-03-25 19:25
> Hey all! #29753 this should have fixed the issues no? cc @phanxuanphucnd

Thank you @ArthurZucker  . The problem has been fixed @danielhanchen

**Comment by ArthurZucker** [comment] 2024-03-26 11:16
Closing then! Thanks all for the input

**Closed by ArthurZucker** 2024-03-26 11:16 UTC
Labels: Feature request
