### ISSUE TITLE
2 Deberta test failures

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#7711] opened 2020-10-11 20:47 UTC
I suspect these are related to recent tokenizer changes:

https://github.com/huggingface/transformers/runs/1236753957?check_suite_focus=true

```
FAILED tests/test_tokenization_deberta.py::DebertaTokenizationTest::test_torch_encode_plus_sent_to_model
FAILED tests/test_modeling_deberta.py::DebertaModelIntegrationTest::test_inference_classification_head
```

**Comment by LysandreJik** [comment] 2020-10-12 07:37
Duplicate of https://github.com/huggingface/transformers/issues/7565

Working on it in https://github.com/huggingface/transformers/pull/7645

**Closed by LysandreJik** 2020-10-12 07:37 UTC
