### ISSUE TITLE
OOM with mixed precision inference on OPT1.3B

### ISSUE THREAD

**Issue by grigorn** [huggingface/transformers#29354] opened 2024-02-28 21:50 UTC
### System Info

- `transformers` version: 4.37.1
- Platform: Linux-5.15.0-87-generic-x86_64-with-glibc2.35
- Python version: 3.10.10
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.23.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.2.1+cu121 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am getting OOM error for this code on 40GB A100. 
```python
from transformers import AutoModelForCausalLM
import torch
model = AutoModelForCausalLM.from_pretrained('facebook/opt-1.3b').cuda()
inpt = torch.randint(0, 1000, (1, 2048))
with torch.autocast(device_type='cuda', dtype=torch.float16):
    out = model(inpt.cuda())
```
But usual inference works
```python
from transformers import AutoModelForCausalLM
import torch
model = AutoModelForCausalLM.from_pretrained('facebook/opt-1.3b').cuda()
inpt = torch.randint(0, 1000, (1, 2048))
out = model(inpt.cuda())
```

### Expected behavior

If I do model.half() inference works but I expected the first code work too without any OOM as full precision inference is ok.

**Comment by younesbelkada** [comment] 2024-02-29 01:55
Hi @grigorn 
I suspect you are getting this because you did not wrapped your inference with `torch.no_grad()` context manager. Can you try again by adding `torch.no_grad()`

**Comment by younesbelkada** [comment] 2024-02-29 09:00
I agree it is strange, at the same time I feel this is quite orthogonoal to transformers, are you able to repro the same behaviour with a pure `torch.nn.Module` ?

**Comment by grigorn** [comment] 2024-02-29 09:06
No, I have not done that. What do you mean by "orthogonal to transformers"? And If I want to to train the model in mixed precision without Trainer, is this the only way?

**Comment by grigorn** [comment] 2024-03-01 13:56
I also tried running running 100 forward passes on input size of 1024. FP32 took 21 seconds using 23GB memory, fp16 4.74 seconds using 27GBs memory.

**Comment by ArthurZucker** [comment] 2024-03-02 04:18
Probably a duplicate of #25419

**Closed** 2024-04-07 08:03 UTC
