### ISSUE TITLE
Hight CPU and low GPU on XLNet

### ISSUE THREAD

**Issue by laiviet** [huggingface/transformers#1529] opened 2019-10-16 01:56 UTC
## 🐛 Bug

I am running Bert, GPT, GPT2, XLNET. I got very high CPU usage (e.g. 16 cores) with  XLNet while the others (Bert, GPT, GPT2) dont.

For BERT, GPT, GPT2: CPU 1 cores, 100%GPU 
For XLNet: CPU 16 cores, 50 to 60% GPU 

Is there any hidden implementation which requires CPU?

Model I am using (XLNet....): XLNET

Language I am using the model on: English

The problem arise when using:
* [ ] the official example scripts: (give details)
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details)

## To Reproduce

1.
2.
3.

## Environment

* OS: Ubuntu 18.04
* Python version: 3.6
* PyTorch version: 1.0
* PyTorch Transformers version (or branch): pytorch_transformers 1.2.0
* Using GPU ? RTX 2080 TI
* Distributed of parallel setup ? No
* Any other relevant information:

**Comment by weili-ict** [comment] 2019-11-04 14:56
I also meet the above problem with XLNet. The GPU usage is very low and unstable, but the CPU usage is very high. The running speed is very low.

Are there any ops running on CPU rather than GPU in your XLNet implementation? How to improve the GPU usage and speed up the running speed ? Thanks!

**Comment by iedmrc** [comment] 2019-12-04 21:34
Does it occur while training or predicting? Are you sure your gpu is available (to PyTorch or TensorFlow)? What do logs say?

**Comment by BramVanroy** [comment] 2020-01-17 08:55
It is likely that this is caused by the tokenisation rather than the model training. Tokenisation typically happens on the CPU, the token_ids are then transferred to the GPU and from then on out the training happens on the GPU.

**Closed** 2020-03-24 09:36 UTC
Labels: wontfix

**Comment by yourh** [comment] 2020-06-16 11:41
The same problem. How to solve it?
