### ISSUE TITLE
_prepare_4d_causal_attention_mask doesn't work with torch.compile

### ISSUE THREAD

**Issue by PhilJd** [huggingface/transformers#27789] opened 2023-12-01 11:31 UTC
### System Info

Transformers version: 4.35.2
Pytorch version: 2.1.1+cu118
Python version: 3.11

### Who can help?

Tagging @ArthurZucker as the original author

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code to reproduce
```python
import torch
import torch.nn as nn
from transformers.modeling_attn_mask_utils import _prepare_4d_causal_attention_mask

# LLama models use this wrapper but this does not fix the compilation issue.
# if is_torch_fx_available():
#    _prepare_4d_causal_attention_mask = torch.fx.wrap(_prepare_4d_causal_attention_mask)

class Model(nn.Module):

    def forward(self, inputs_embeds):
        batch_size, seq_length, _ = inputs_embeds.shape
        past_key_values_length = 10
        attention_mask = _prepare_4d_causal_attention_mask(
            None, (batch_size, seq_length), inputs_embeds, past_key_values_length
        )
        return attention_mask

model = Model()
model = torch.compile(model, fullgraph=True)
model(torch.ones([1,5, 32]))
```
Gives a torch.compile error:
```
[...]
    return SourcelessBuilder()(tx, val).add_options(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.virtualenvs/pytorch311/lib/python3.11/site-packages/torch/_dynamo/variables/builder.py", line 1650, in __call__
    unimplemented(f"Unexpected type in sourceless builder {type(value)}")
  File "/home/ubuntu/.virtualenvs/pytorch311/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 172, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: Unexpected type in sourceless builder <class 'torch.dtype'>

from user code:
   File "<stdin>", line 6, in forward
  File "/home/ubuntu/.virtualenvs/pytorch311/lib/python3.11/site-packages/transformers/modeling_attn_mask_utils.py", line 197, in _prepare_4d_causal_attention_mask
    attention_mask = attn_mask_converter.to_causal_4d(
```

Note that I could reproduced this by e.g. trying to compile a Llama2 model.

Removing the dtype argument and just setting dtype=torch.float32 in the function body compiles.
I'm not sure whether this is a bug in the torch compiler or unintended usage in transformers, so happy to open an issue there as well if required :)

### Expected behavior

No errors during torch.compile stge.
Let me know if there's something I can do to help debug!

**Comment by ArthurZucker** [comment] 2023-12-01 13:10
Ow nice catch and nice reproducer! 🤗 
I'll try to have a look, otherwise pinging @fxmarty

**Comment by fxmarty** [comment] 2023-12-06 17:25
Hi @PhilJd the issue is fixed in https://github.com/huggingface/transformers/pull/27868. This a bug in PyTorch 2.0/2.1, that is solved in pytorch nightly.

**Closed** 2023-12-08 09:44 UTC

**Comment by PhilJd** [comment] 2023-12-08 10:45
Thanks a lot! :)
