### ISSUE TITLE
Can't down models from huggingface.cn!

### ISSUE THREAD

**Issue by havetry** [huggingface/transformers#8455] opened 2020-11-11 06:49 UTC
## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

## Expected behavior

I want to down model from huggingface.cn, but I can't find the models to down.
![down](https://user-images.githubusercontent.com/49902228/98777922-8bf23780-242c-11eb-90b9-02d86cefac34.png)
But I found the model had been download many times in noverber 9. Something happened I didn't know about? And what should I do to get models that I need?
![have_down](https://user-images.githubusercontent.com/49902228/98778321-23578a80-242d-11eb-9503-c46f3cde25f3.png)

**Comment by julien-c** [comment] 2020-11-11 07:45
Duplicate of #8449

**Closed by julien-c** 2020-11-11 07:45 UTC
