### ISSUE TITLE
ESM esmfold_v1 infer_pdbs method gives TypeError

### ISSUE THREAD

**Issue by maxjeblick** [huggingface/transformers#20120] opened 2022-11-08 11:56 UTC
### System Info

- `transformers` version: 4.24.0
- Platform: Linux-5.4.0-105-generic-x86_64-with-glibc2.31
- Python version: 3.9.12
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@LysandreJik

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
from transformers import EsmForProteinFolding

model = EsmForProteinFolding.from_pretrained("facebook/esmfold_v1").cuda()
pdbs = model.infer_pdbs(["MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG"])
```
gives

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [12], line 1
----> 1 pdbs = model.infer_pdbs(["MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG"])

File ~/PycharmProjects/esm/venv/lib/python3.9/site-packages/transformers/models/esm/modeling_esmfold.py:2318, in EsmForProteinFolding.infer_pdbs(self, seqs, *args, **kwargs)
   2316 def infer_pdbs(self, seqs: List[str], *args, **kwargs) -> List[str]:
   2317     """Returns the pdb (file) string from the model given an input sequence."""
-> 2318     output = self.infer(seqs, *args, **kwargs)
   2319     return self.output_to_pdb(output)

File ~/PycharmProjects/esm/venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File ~/PycharmProjects/esm/venv/lib/python3.9/site-packages/transformers/models/esm/modeling_esmfold.py:2280, in EsmForProteinFolding.infer(self, seqs, residx, with_mask)
   2278 if residx.ndim == 1:
   2279     residx = residx.unsqueeze(0)
-> 2280 return self.forward(
   2281     aatype,
   2282     mask,
   2283     mask_aa=with_mask is not None,
   2284     masking_pattern=with_mask,
   2285     residx=residx,
   2286 )

TypeError: forward() got an unexpected keyword argument 'mask_aa'
```

### Expected behavior

pdb will be calculated correctly.

**Comment by sgugger** [comment] 2022-11-08 15:53
cc @Rocketknight1

**Comment by Rocketknight1** [comment] 2022-11-10 15:44
Hi @maxjeblick, this is caused by those methods being ported directly from `ESMFold` and not being updated to match our implementation. I'm working on a fix now! In the meantime you can use the code from our [example notebook for protein folding](https://github.com/huggingface/notebooks/blob/main/examples/protein_folding.ipynb) to convert model outputs to PDB.

**Comment by Rocketknight1** [comment] 2022-11-10 16:48
@maxjeblick fixed on main now!

**Closed** 2022-11-10 16:48 UTC
