### ISSUE TITLE
Running summarization with default model fails. 4.27.0.dev0

### ISSUE THREAD

**Issue by jojivk73** [huggingface/transformers#21865] opened 2023-03-01 04:17 UTC
### System Info

When runining examples/tensorflow/summarization/run_summarization.py
as given in README, 
python run_summarization.py  \
--model_name_or_path facebook/bart-base \
--dataset_name cnn_dailymail \
--dataset_config "3.0.0" \
--output_dir /tmp/tst-summarization  \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 16 \
--num_train_epochs 3 \
--do_train \
--do_eval

it fails as below.

![image](https://user-images.githubusercontent.com/14943401/222041742-82660acf-6fa4-40a4-af92-38a81044ddf0.png)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Copy script in README to a file
2. Run the script

### Expected behavior

Should run without issues as it is example given in README

**Comment by sgugger** [comment] 2023-03-01 14:03
cc @Rocketknight1

**Comment by Rocketknight1** [comment] 2023-03-01 15:56
Hi @jojivk73, thanks for the bug report! We've reproduced the issue - the cause is that the `transformers` library is currently transitioning to using standardized native Keras layers for as many purposes as possible, and deprecating the previous setup where we often had ad-hoc model-specific solutions. 

One consequence of the transition is that BART's embeddings used to store their weights in `embeddings.weight`, but now that they've been swapped to a Keras `Embedding` layer, the weights are in `embeddings.embeddings`. We missed this issue in the example code during the transition, but we're preparing a PR to fix it immediately. I'll ping you as soon as it's ready.

**Comment by Rocketknight1** [comment] 2023-03-01 16:57
@jojivk73 PR is merged. Please install the latest version from `main` and let me know if you have any other problems!

**Closed** 2023-03-01 16:57 UTC
