### ISSUE TITLE
Inconsistent results between LlamaTokenizer and LlamaTokenizerFast

### ISSUE THREAD

**Issue by zzzzzzrc** [huggingface/transformers#27230] opened 2023-11-02 09:29 UTC
### System Info

transformers==4.34.1
tokenizers==0.14.1

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction
```
import transformers

fast = transformers.AutoTokenizer.from_pretrained('meta-llama/Llama-2-7b-hf', use_fast=True)
slow = transformers.AutoTokenizer.from_pretrained('meta-llama/Llama-2-7b-hf', use_fast=False)

>>> fast.encode("abs</s>USER")
[1, 6425, 2, 3148, 1001]
>>> slow.encode("abs</s>USER")
[1, 6425, 2, 11889]
>>> fast.decode([1, 6425, 2, 3148, 1001])
'<s> abs</s> USER'
>>> slow.decode([1, 6425, 2, 11889])
'<s> abs</s>USER'
```
fast tokenizer would add a whitespace between eos and USER

### Expected behavior

fast and slow tokenizer get the same results

**Comment by ArthurZucker** [comment] 2023-11-06 13:49
Hey! This is a duplicate of #26318, #26455, #25881, and will be fixed in #26678

**Closed** 2023-12-11 08:04 UTC
