### ISSUE TITLE
Using add_generation_prompt with tokenizer.apply_chat_template does not add the required assistant start token

### ISSUE THREAD

**Issue by srikant86panda** [huggingface/transformers#28355] opened 2024-01-05 09:29 UTC
### System Info

Version:
transformers: 4.36.1 and transformers @ git+https://github.com/huggingface/transformers.git@5d36025ca13d05151b7a0c761e90d429c4644a30

Tokenizer: tokenizers==0.15.0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running with 
```python
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.2")

messages = [
    {"role": "user", "content": "What is your favourite condiment?"},
    {"role": "assistant", "content": "Well, I'm quite partial to a good squeeze of fresh lemon juice. It adds just the right amount of zesty flavour to whatever I'm cooking up in the kitchen!"},
    {"role": "user", "content": "Do you have mayonnaise recipes?"},

]
encodeds = tokenizer.apply_chat_template(messages, add_generation_prompt=False, tokenize=False)
print(f'without add_generation_prompt: {encodeds}')
encodeds = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)
print(f'with    add_generation_prompt: {encodeds}')
```

### Expected behavior

With add_generation_prompt with tokenizer.apply_chat_template does should add the required assistant start token as discussed here: https://github.com/huggingface/transformers/issues/26539

Attached is a screenshot for reference
![Screenshot 2024-01-05 at 2 51 47 PM](https://github.com/huggingface/transformers/assets/18262494/87542f95-c259-47ae-abf0-61eefcaf1253)

**Comment by ArthurZucker** [comment] 2024-01-05 11:30
cc @Rocketknight1

**Comment by Rocketknight1** [comment] 2024-01-08 15:02
Hi @srikant86panda, Mistral and Mixtral both use the LLaMA prompt format, which does not include a special token at the start of assistant responses. Instead, they enforce that all conversations must alternate user/assistant/user/assistant, and the assistant response is always written immediately after the user message is finished with the `[/INST]` token.

As a result, `add_generation_prompt` does not have any effect for those models, and this is the correct and intended behaviour. I'm going to close this issue for now, but please let me know if you have any further problems or questions!

**Closed by Rocketknight1** 2024-01-08 15:02 UTC

**Comment by srikant86panda** [comment] 2024-01-09 16:54
@Rocketknight1 thanks for clarifying it. My concern is good to be closed.
