### ISSUE TITLE
Convert llama-2 to hf error

### ISSUE THREAD

**Issue by xuanzhangyang** [huggingface/transformers#33746] opened 2024-09-27 06:54 UTC
### System Info

transformer version:   4.46.0  - install from master
pytorch version:  1.9
python version: 3.8

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

(pytorch1.9) xxx@xxx-G5500:~/code/pytorch/llama$ ls llama-2-7b

checklist.chk consolidated.00.pth params.json tokenizer_checklist.chk tokenizer.model
(pytorch1.9) xxx@xxx-G5500:~/code/pytorch/llama$ python ../hunningface/transformers/src/transformers/models/llama/convert_llama_weights_to_hf.py --input_dir ./llama-2-7b --model_size 7B --output_dir ./llama-2-7b-hf

### Expected behavior

Error mesage:  
`You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
Traceback (most recent call last):
  File "/home/xuan/code/pytorch/hunningface/transformers/src/transformers/convert_slow_tokenizer.py", line 1591, in convert_slow_tokenizer
    return TikTokenConverter(
  File "/home/xuan/code/pytorch/hunningface/transformers/src/transformers/convert_slow_tokenizer.py", line 1491, in converted
    tokenizer = self.tokenizer()
  File "/home/xuan/code/pytorch/hunningface/transformers/src/transformers/convert_slow_tokenizer.py", line 1483, in tokenizer
    vocab_scores, merges = self.extract_vocab_merges_from_model(self.vocab_file)
  File "/home/xuan/code/pytorch/hunningface/transformers/src/transformers/convert_slow_tokenizer.py", line 1458, in extract_vocab_merges_from_model
    bpe_ranks = load_tiktoken_bpe(tiktoken_url)
  File "/home/xuan/anaconda3/envs/pytorch1.9/lib/python3.8/site-packages/tiktoken/load.py", line 148, in load_tiktoken_bpe
    return {
  File "/home/xuan/anaconda3/envs/pytorch1.9/lib/python3.8/site-packages/tiktoken/load.py", line 150, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../hunningface/transformers/src/transformers/models/llama/convert_llama_weights_to_hf.py", line 479, in <module>
    main()
  File "../hunningface/transformers/src/transformers/models/llama/convert_llama_weights_to_hf.py", line 457, in main
    write_tokenizer(
  File "../hunningface/transformers/src/transformers/models/llama/convert_llama_weights_to_hf.py", line 367, in write_tokenizer
    tokenizer = tokenizer_class(input_tokenizer_path)
  File "/home/xuan/code/pytorch/hunningface/transformers/src/transformers/models/llama/tokenization_llama_fast.py", line 157, in __init__
    super().__init__(
  File "/home/xuan/code/pytorch/hunningface/transformers/src/transformers/tokenization_utils_fast.py", line 138, in __init__
    fast_tokenizer = convert_slow_tokenizer(self, from_tiktoken=True)
  File "/home/xuan/code/pytorch/hunningface/transformers/src/transformers/convert_slow_tokenizer.py", line 1596, in convert_slow_tokenizer
    raise ValueError(
ValueError: Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']
`

**Comment by LysandreJik** [comment] 2024-09-27 09:59
cc @itazap if you have the bandwidth :)

**Comment by itazap** [comment] 2024-09-27 12:16
hey @xuanzhangyang - I'm unable to reproduce the error, is your `llama-2-7b` a git clone of `https://huggingface.co/meta-llama/Llama-2-7b` ?

**Comment by xuanzhangyang** [comment] 2024-09-29 09:30
> hey @xuanzhangyang - I'm unable to reproduce the error, is your `llama-2-7b` a git clone of `https://huggingface.co/meta-llama/Llama-2-7b` ?

I use https://github.com/meta-llama/llama.git

**Comment by insidesecurity-yhojann-aguilera** [comment] 2024-10-05 21:34
The `transformers` package is broken for now. It is not possible to run models from Hugging Face `transformers` at the moment.

**Comment by sbrunswi** [comment] 2024-10-05 23:48
I have the same issue!

**Comment by ArthurZucker** [comment] 2024-10-06 08:47
@mjbommar I can't reproduce

**Comment by ArthurZucker** [comment] 2024-10-06 08:52
The warning is missleading, but you need `sentencepiece` installed if the tokenizer you are trying to load does not have a `tokenizer.json` (FYI @itazap )

**Comment by digbangbang** [comment] 2024-10-06 14:03
how to solve the problem?

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
Traceback (most recent call last):
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 1592, in convert_slow_tokenizer
    ).converted()
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 1489, in converted
    tokenizer = self.tokenizer()
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 1482, in tokenizer
    vocab_scores, merges = self.extract_vocab_merges_from_model(self.vocab_file)
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 1458, in extract_vocab_merges_from_model
    bpe_ranks = load_tiktoken_bpe(tiktoken_url)
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/tiktoken/load.py", line 145, in load_tiktoken_bpe
    return {
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/tiktoken/load.py", line 147, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/li/reweight/convert.py", line 509, in <module>
    main()
  File "/home/li/reweight/convert.py", line 487, in main
    write_tokenizer(
  File "/home/li/reweight/convert.py", line 393, in write_tokenizer
    tokenizer = tokenizer_class(input_tokenizer_path)
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 157, in __init__
    super().__init__(
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 138, in __init__
    fast_tokenizer = convert_slow_tokenizer(self, from_tiktoken=True)
  File "/home/li/reweight/miniconda3/envs/eval/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 1594, in convert_slow_tokenizer
    raise ValueError(
ValueError: Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']

**Comment by digbangbang** [comment] 2024-10-07 12:05
Thanks, I have fixed it by `pip install sentencepiece` @ArthurZucker

**Comment by LysandreJik** [comment] 2024-10-07 16:33
This seems like an error message that should be edited, feel free to open a PR!

**Comment by johnsutor** [comment] 2024-10-07 18:19
@ArthurZucker I mentioned the issue to the tiktoken maintainers. Is there anything I should try in the interim? I tried installing sentencepiece, tried downgrading tiktoken, and more to no avail :(

**Comment by johnsutor** [comment] 2024-10-07 18:45
Update: uninstalled and then re-installed sentencepiece and now it works!

**Comment by ShubhamS021** [comment] 2024-10-08 14:17
Restart the notebook and it will work

**Comment by Wafaa014** [comment] 2024-10-10 12:04
I have tried all the mentioned solutions here and it doesn't work

**Comment by ArthurZucker** [comment] 2024-10-10 12:50
@Wafaa014 can you provide a reproducer?

**Comment by ArthurZucker** [comment] 2024-10-10 13:02
Okay, will have a look but I don't understand why you are not using LlamaTokenizerFast, as it should be faster

**Comment by ArthurZucker** [comment] 2024-10-10 13:02
<img width="729" alt="image" src="https://github.com/user-attachments/assets/7c984c39-f95a-4846-81e6-f5a7890c7f4b">
Could not reproduce sadly btw

**Comment by Wafaa014** [comment] 2024-10-10 13:08
the fast tokenizer throws the tiktoken error. 
This is weird. Are you creating a new env with the pip freeze to reproduce?

**Comment by Wafaa014** [comment] 2024-10-10 13:32
Oh thank you so much! Deleting the cache does solve it! I appreciate your help both @mjbommar @ArthurZucker

**Comment by ArthurZucker** [comment] 2024-10-14 06:53
Cool closing this as solved then! 🤗

**Closed by ArthurZucker** 2024-10-14 06:53 UTC
Labels: Core: Tokenization, Fast Tokenizers, bug

**Comment by gaoCleo** [comment] 2024-11-28 02:02
> Update: uninstalled and then re-installed sentencepiece and now it works!

I found that I didn't have sentencepiece installed, so I ran `pip install sentencepiece` to fix the problem. And it works.
