### ISSUE TITLE
TFDistilBertModelTest.test_pt_tf_model_equivalence thrown while merging after PR

### ISSUE THREAD

**Issue by TheEdoardo93** [huggingface/transformers#2240] opened 2019-12-20 14:25 UTC
## 🐛 Bug

I've seen that some PRs failed because of the same error, such as #2239 (today) and #2237 (today). If I'm not remember wrong, there is also another PR in the last days involved @rlouf that he had the same error. Even if the changes made not affect `DistilBertModel` such as #2237, this error occurs!
Question: **Is it a bug in Transformers or a bug in our code submitted?**

## To Reproduce

Steps to reproduce the behavior: after submitting a PR to Transformers library, it occurs
```
=================================== FAILURES ===================================
______________ TFDistilBertModelTest.test_pt_tf_model_equivalence ______________

self = <transformers.tests.modeling_tf_distilbert_test.TFDistilBertModelTest testMethod=test_pt_tf_model_equivalence>

    def test_pt_tf_model_equivalence(self):
        if not is_torch_available():
            return
    
        import torch
        import transformers
    
        config, inputs_dict = self.model_tester.prepare_config_and_inputs_for_common()
    
        for model_class in self.all_model_classes:
            pt_model_class_name = model_class.__name__[2:]  # Skip the "TF" at the beggining
            pt_model_class = getattr(transformers, pt_model_class_name)
    
            config.output_hidden_states = True
            tf_model = model_class(config)
            pt_model = pt_model_class(config)
    
            # Check we can load pt model in tf and vice-versa with model => model functions
            tf_model = transformers.load_pytorch_model_in_tf2_model(tf_model, pt_model, tf_inputs=inputs_dict)
            pt_model = transformers.load_tf2_model_in_pytorch_model(pt_model, tf_model)
    
            # Check predictions on first output (logits/hidden-states) are close enought given low-level computational differences
            pt_model.eval()
            pt_inputs_dict = dict((name, torch.from_numpy(key.numpy()).to(torch.long))
                                  for name, key in inputs_dict.items())
            with torch.no_grad():
                pto = pt_model(**pt_inputs_dict)
            tfo = tf_model(inputs_dict, training=False)
            tf_hidden_states = tfo[0].numpy()
            pt_hidden_states = pto[0].numpy()
            tf_hidden_states[np.isnan(tf_hidden_states)] = 0
            pt_hidden_states[np.isnan(pt_hidden_states)] = 0
            max_diff = np.amax(np.abs(tf_hidden_states - pt_hidden_states))
>           self.assertLessEqual(max_diff, 2e-2)
E           AssertionError: 3.107201 not less than or equal to 0.02

transformers/tests/modeling_tf_common_test.py:139: AssertionError
```

## Expected behavior

No error was thrown.

## Environment

* OS: **Ubuntu 16.04**
* Python version: **3.6.9**
* PyTorch version: **1.3.1**
* PyTorch Transformers version (or branch): **master**
* Using GPU ? **Indifferent**
* Distributed of parallel setup ? **Indifferent**
* Any other relevant information:

**Comment by aaugustin** [comment] 2019-12-20 20:41
I've seen the same error when running the test suite locally.

**Comment by aaugustin** [comment] 2019-12-21 12:08
I think it was fixed by d36680df546a9d4a20c58c0eab2b14ee054436ca

**Comment by julien-c** [comment] 2019-12-21 14:47
I know how to reproduce/debug this particular failure so I'll take a look on monday (unless someone beats me to it)

**Comment by julien-c** [comment] 2019-12-24 00:22
aaarg, I can't reproduce it locally anymore.

**Closed** 2020-04-14 23:25 UTC
Labels: wontfix
