### ISSUE TITLE
Encoding special tokens

### ISSUE THREAD

**Issue by pglock** [huggingface/transformers#2080] opened 2019-12-06 09:21 UTC
## 🐛 Bug

In version 2.2.1 encoding special tokens changed.

```python
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokenizer.decode(tokenizer.encode("[CLS] hello world [SEP]", add_special_tokens=False))
```
output: `'[ cls ] hello world [ sep ]'`

For version `transformers==2.2.0` the output is: `'[CLS] hello world [SEP]'`

**Comment by luke4u** [comment] 2019-12-06 11:10
I got the same issue for version 2.2.1.

**Comment by makcedward** [comment] 2019-12-06 17:23
I also meet this issue and you may check out the possible root cause from #2052. 

My workaround is backoff to 2.1.1 version.

**Comment by LysandreJik** [comment] 2019-12-06 21:17
Should have been fixed with https://github.com/huggingface/transformers/pull/2051

**Closed** 2019-12-09 10:45 UTC
