### ISSUE TITLE
Invalid pytorch_model.bin for TAPAS-large

### ISSUE THREAD

**Issue by saichandrapandraju** [huggingface/transformers#10623] opened 2021-03-10 03:14 UTC
Hi,
I was downloading `google/tapas-large` binaries from [HF models](https://huggingface.co/google/tapas-large/tree/main) and for pytorch_model.bin, a zip file was getting downloaded which is not a `bin` file like other models.

folder structure is like - `archive/data/.*File`, `archive/data.pkl` ,` archive/version.File`. Same for tapas-base as well. 
These cannot be used for loading a model (`TapasForQuestionAnswering.from_pretrained('path/to/binaries directory')`)

plz suggest how to proceed further..

**Comment by NielsRogge** [comment] 2021-03-10 10:01
Hi, not sure why this happens, cc @julien-c.

A workaround is to load the model using `model = TapasModel.from_pretrained("google/tapas-base")` and then use `model.save_pretrained("./")` to save the `config.json` and `pytorch_model.bin` file to a local directory.

**Comment by julien-c** [comment] 2021-03-10 11:27
I don't remember how those models were uploaded so not sure why this is happening.

cc'ing @Pierrci for visibility

In the meantime you can just rename the file to .bin

**Comment by LysandreJik** [comment] 2021-03-10 12:01
@saichandrapandraju the file on tapas-large is a bin file, but since pytorch 1.6.0, bin files are now zip-based. You can check the documentation of [torch.save](https://pytorch.org/docs/stable/generated/torch.save.html) which states:

> The 1.6 release of PyTorch switched torch.save to use a new zipfile-based file format. torch.load still retains the ability to load files in the old format. If for any reason you want torch.save to use the old format, pass the kwarg _use_new_zipfile_serialization=False.

**Comment by julien-c** [comment] 2021-03-10 17:43
Ok will close this as:
- we found the root cause but it's outside our control (`lfs` adds an auto content-type)
- there are several workarounds like `git clone`ing the repo or just renaming the file (`from_pretrained` also works as usual)

Thanks for investigating @Pierrci and @LysandreJik 🥇

**Closed by julien-c** 2021-03-10 17:43 UTC
