### ISSUE TITLE
issue with loading pretrained model using DeepSpeed Zero Stage 3 

### ISSUE THREAD

**Issue by pacman100** [huggingface/transformers#17336] opened 2022-05-18 19:01 UTC
### System Info

```shell
- `transformers` version: 4.19.0.dev0
- Platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.5.1
- PyTorch version (GPU?): 1.12.0.dev20220505+cu113 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes (deepspeed zero stage-3)
```

### Who can help?

@stas00 @sgugger 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to reproduce the behaviour:
1. Official `run_glue.py` [script](https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue.py)
2. Below ZERO Stage-3 Config `zero3_config.json`:
```json
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto",
            "torch_adam": true,
            "adam_w_mode": true
        }
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto",
            "total_num_steps": "auto"
        }
    },
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```
3. bash script to run the finetuning of `bert-base-uncased` on MRPC dataset using ZERO Stage-3.
```bash
#!/bin/bash

time torchrun --nproc_per_node=2 run_glue.py \
--task_name "mrpc" \
--max_seq_len 128 \
--model_name_or_path "bert-base-uncased" \
--output_dir "./glue/mrpc_deepspeed_stage3_trainer" \
--overwrite_output_dir \
--do_train \
--evaluation_strategy "epoch" \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 16 \
--gradient_accumulation_steps 1 \
--learning_rate 2e-5 \
--weight_decay 0.0 \
--max_grad_norm 1.0 \
--num_train_epochs 3 \
--lr_scheduler_type "linear" \
--warmup_steps 50 \
--logging_steps 100 \
--fp16 \
--fp16_full_eval \
--optim "adamw_torch" \
--report_to "wandb" \
--deepspeed "zero3_config.json"
```

4. Relevant output snippets. The first one shows the weird behaviour wherein the model isn't being properly initialized with the pretrained weights. The second shows the eval metrics showing the random performance.

![model init](https://user-images.githubusercontent.com/13534540/169131572-a1165baa-6713-4fce-a0be-db2e062b605a.png)
![bad performance](https://user-images.githubusercontent.com/13534540/169134622-6970e0ae-a0c5-44f6-bab3-129af3f5b5d2.png)

### Expected behavior

Model being properly initialized with the pretrained weights when using DeepSpeed ZERO Stage-3. This should resolve the bad model performance being observed.

**Comment by stas00** [comment] 2022-05-19 00:38
sounds like a potential problem with pt-nightly?

It works just fine on pt-1.11:

```
torchrun --nproc_per_node=2 examples/pytorch/text-classification/run_glue.py --task_name "mrpc" --max_seq_len 128 --model_name_or_path "bert-base-uncased" --output_dir xxx --overwrite_output_dir --do_train --evaluation_strategy "epoch" --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --gradient_accumulation_steps 1 --learning_rate 2e-5 --weight_decay 0.0 --max_grad_norm 1.0 --num_train_epochs 3 --lr_scheduler_type "linear" --warmup_steps 50 --logging_steps 100 --fp16 --fp16_full_eval --optim "adamw_torch" --deepspeed tests/deepspeed/ds_config_zero3.json
```

**Comment by stas00** [comment] 2022-05-19 01:05
the deepspeed config difference is:
```
-        "type": "WarmupDecayLR",
+        "type": "WarmupLR",
```

but it shouldn't cause an issue with the pre-trained weights. I wonder why you see a different behavior.

**Comment by pacman100** [comment] 2022-05-19 04:28
Hello Stas, Thank you for all the deep dive and prompt reply. I just now found a minor change that I had done in `run_glue.py`. It is the following wherein I add ` ignore_mismatched_sizes=True,` to `from_pretrained` method. This is done so that I can load the pre-trained model with different number of output classes than the classification problem at hand. 
```diff
model = AutoModelForSequenceClassification.from_pretrained(
        model_args.model_name_or_path,
        from_tf=bool(".ckpt" in model_args.model_name_or_path),
        config=config,
        cache_dir=model_args.cache_dir,
        revision=model_args.model_revision,
-        use_auth_token=True if model_args.use_auth_token else None
+       use_auth_token=True if model_args.use_auth_token else None,
+        ignore_mismatched_sizes=True,
    )
```
I can confirm that this is causing the issue. It is resulting in the shape mismatch warning and then poor performance. Below are the plots with and without this change.
![Screenshot 2022-05-19 at 9 57 33 AM](https://user-images.githubusercontent.com/13534540/169205000-5f1931f2-2a44-4495-8e44-7a7eabcc73b2.png)

**Comment by stas00** [comment] 2022-05-19 04:35
Great to hear you found the cause.

In general when you use deepspeed ZeRO stage-3 and you see a shape that's of size 0, it's because the weights are sharded - the internals have all kinds of places where the weights are reconsolidated for you at the right places, but if you go on your own you have to do it yourself at times. Just grep for `deepspeed.zero.GatheredParameters` for examples.

If you don't need any additional help you can close the Issue at any time.

If you have further questions please don't hesitate to ask.

**Comment by pacman100** [comment] 2022-05-19 04:51
I think fixing this would be important as many users would use pretrained models to fine-tune on their task which will likely have different number of output classes than the pretrained model. Maybe option/choice/bool flag to not have `deepspeed.zero.init` or the logic in `from_pretrained` to load and partition layers on different GPUs would resolve this for small to medium models.

**Comment by stas00** [comment] 2022-05-19 04:59
Please give me a full setup that I can reproduce your issue with and I will try to come up with a solution.

And also if you write your own trainer you definitely aren't forced to go through `deepspeed.zero.init` - it doesn't happen by default, you have to call it. See: https://deepspeed.readthedocs.io/en/latest/zero3.html#constructing-massive-models

Also `deepspeed.zero.Init(enabled=False)` will not pre-shard the model at load time. I wonder if we could ask the Deepspeed developers to add a new ds_config file variable that could control that via the config file - that way the user can easily turn it off at will. What do you think?

**Comment by pacman100** [comment] 2022-05-19 07:11
Exact setup to reproduce the above behaviour:
1. Official `run_glue.py` [script](https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue.py) with the following change. The exact updated script for quick run 
```diff
model = AutoModelForSequenceClassification.from_pretrained(
        model_args.model_name_or_path,
        from_tf=bool(".ckpt" in model_args.model_name_or_path),
        config=config,
        cache_dir=model_args.cache_dir,
        revision=model_args.model_revision,
-        use_auth_token=True if model_args.use_auth_token else None
+       use_auth_token=True if model_args.use_auth_token else None,
+        ignore_mismatched_sizes=True,
    )
```
3. Below ZERO Stage-3 Config `zero3_config.json`:
```json
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto",
            "torch_adam": true,
            "adam_w_mode": true
        }
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto",
            "total_num_steps": "auto"
        }
    },
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```
4. bash script to run the finetuning of `bert-base-uncased` on MRPC dataset using ZERO Stage-3.
```bash
#!/bin/bash

time torchrun --nproc_per_node=2 run_glue.py \
--task_name "mrpc" \
--max_seq_len 128 \
--model_name_or_path "bert-base-uncased" \
--output_dir "./glue/mrpc_deepspeed_stage3_trainer" \
--overwrite_output_dir \
--do_train \
--evaluation_strategy "epoch" \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 16 \
--gradient_accumulation_steps 1 \
--learning_rate 2e-5 \
--weight_decay 0.0 \
--max_grad_norm 1.0 \
--num_train_epochs 3 \
--lr_scheduler_type "linear" \
--warmup_steps 50 \
--logging_steps 100 \
--fp16 \
--fp16_full_eval \
--optim "adamw_torch" \
--report_to "wandb" \
--deepspeed "zero3_config.json"
```

**Comment by pacman100** [comment] 2022-05-19 11:57
The issue is because of the logic at [modeling_utils.py#L2182](https://github.com/huggingface/transformers/blob/a4386d7e405712fb9e9ad1066828ded3174f6a61/src/transformers/modeling_utils.py#L2182). Here, the zero-3 state dict with partitions are being checked against the pretrained model state_dict, which will result in all keys being mismatched and deleted from pretrained model state_dict.

**Comment by stas00** [comment] 2022-05-20 21:01
Thank you, @pacman100 

Please try this PR https://github.com/huggingface/transformers/pull/17373

**Comment by pacman100** [comment] 2022-05-24 06:49
Hello @stas00, yes the above PR solves this issue. Thank you 😄 . Below are the plots finetuning `microsoft/deberta-v2-xlarge-mnli` on MRPC dataset. 
<img width="1157" alt="Screenshot 2022-05-24 at 12 18 30 PM" src="https://user-images.githubusercontent.com/13534540/169966505-98b916d0-579d-4b62-be63-7b61f664ebe4.png">

**Closed** 2022-09-25 15:02 UTC
Labels: DeepSpeed, bug
