### ISSUE TITLE
Error while converting distilbart-mnli-12-1 model to ONNX

### ISSUE THREAD

**Issue by farzanehnakhaee70** [huggingface/transformers#15123] opened 2022-01-12 13:34 UTC
After converting `distilbart-mnli-12-1` to ONNX, while testing the onnx model, I get this issue:
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: \[ONNXRuntimeError\] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Expand node. Name:'Expand_74' Status Message: invalid expand shape
```

After lots of investigation I understand that the problem is existed with `shift_tokens_right` function in `modeling_bart.py` code.

I edit the function to this:

```
def shift_tokens_right(input_ids: torch.Tensor, pad_token_id: int, decoder_start_token_id: int):
    """
    Shift input ids one token to the right.
    """
    shifted_input_ids = input_ids.new_zeros(input_ids.shape)
    shifted_input_ids[:, 1:] = input_ids[:, :-1].clone()
    shifted_input_ids[:, 0] = torch.full((input_ids.shape[0],),decoder_start_token_id)

    assert pad_token_id is not None, "self.model.config.pad_token_id has to be defined."
    # # replace possible -100 values in labels by `pad_token_id`
    shifted_input_ids.masked_fill_(shifted_input_ids == -100, pad_token_id)

    return shifted_input_ids
```
Problem totally solved. The issue is existed with ONNX converter where do not perform correctly while there is broadcasting.

Is it possible to edit the repository and merge these changes to yours?

**Comment by patil-suraj** [comment] 2022-01-12 14:11
cc @lewtun @michaelbenayoun

**Comment by farzanehnakhaee70** [comment] 2022-01-12 15:35
Welcome!
I see your major changes in your configuration which largely improves usability for other tasks. But this error will not be solved without changing the code as I mentioned.

The major issue is that although we add `dynamix_axis` in conversion script, but due to the error of broadcasting, the output of this function became fixed with regard to the batch_size of the dummy input. Therefore, when running the model after conversion with batch size different from the batch size of the dummy input, this error will raise.

**Comment by lewtun** [comment] 2022-01-12 16:17
Thank you for the extra context about the batch size :)

However, I am not able to reproduce the problem you reported. For example, suppose we export the model using the command I used in my previous comment:

```bash
# Export model with default features (i.e. just `BartModel`)
python -m transformers.onnx --model=valhalla/distilbart-mnli-12-1 onnx/
```

We can then load this model into an ONNX Runtime `InferenceSession` as follows:

```python
from transformers import AutoTokenizer, AutoModel

model_ckpt = "valhalla/distilbart-mnli-12-1"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

bs = 16 # batch size
ort_session = ort.InferenceSession("onnx/model.onnx")
onnx_named_outputs = ["last_hidden_state"]

inputs = tokenizer(["Hello, my name is Lewis"] * bs, return_tensors="np")
decoder_inputs = tokenizer(["Hello"] * bs, return_tensors="np")
all_inputs = {
    "input_ids": inputs["input_ids"],
    "attention_mask": inputs["attention_mask"],
    "decoder_input_ids": decoder_inputs["input_ids"],
    "decoder_attention_mask": decoder_inputs["attention_mask"],
}
onnx_outputs = ort_session.run(onnx_named_outputs, all_inputs)
```

This runs without error using the source install of `transformers`. For comparison, we can find the batch size used in the dummy inputs during the conversion as follows:

```python
from transformers.models.bart import BartConfig, BartOnnxConfig

config = BartConfig.from_pretrained(model_ckpt)
onnx_config = BartOnnxConfig(config)
dummy_inputs = onnx_config.generate_dummy_inputs(tokenizer, framework=TensorType.NUMPY)
# Returns (batch_size, seq_len) = (2,8)
dummy_inputs["input_ids"].shape
```

So you can see that the dummy inputs have a batch size of 2, while the inference example I created uses a batch size of 16. 

Could you please share a minimal reproducible example with the problem you're facing (e.g. a Colab notebook)?

**Comment by farzanehnakhaee70** [comment] 2022-01-13 06:30
Thanks a lot for your complete consideration.
I convert one model for `sentence classification` task and it doesn't have any `decoder_input_ids` and `decoder_attention_mask` as input. The only inputs are `input_ids` and `attentio_mask` which is shown by netron.
If these inputs are availabe for the model, then we do not have any problem because the `shift_tokens_right` function will no be used any more.
Would you please tell me how I can convert my model that these two inputs are also defined as the input as the same as what you have done?

**Comment by lewtun** [comment] 2022-01-13 14:18
Ah, now I am able to reproduce the problem - the missing step was to specify explicitly that we should use the `sequence-classification` feature 😄  

For example, the following fails:

```python
import onnxruntime as ort
from transformers import AutoTokenizer, AutoModel

# Export the model
model_ckpt = "valhalla/distilbart-mnli-12-1"
onnx_path = f"onnx/bart-large-clf/"
!python -m transformers.onnx --model={model_ckpt} --feature="sequence-classification" {onnx_path}

# Run with ONNX Runtime
ort_session = ort.InferenceSession(f"{onnx_path}model.onnx")
# Note we have `logits` for sequence classification heads
onnx_named_outputs = ["logits"]
# This works because the dummy inputs have batch_size=2
inputs = tokenizer(["I loved this movie!"] * 2, return_tensors="np")
onnx_outputs = ort_session.run(onnx_named_outputs, dict(inputs))
# This fails
inputs = tokenizer(["I loved this movie!"] * 3, return_tensors="np")
onnx_outputs = ort_session.run(onnx_named_outputs, dict(inputs))
```

And great detective work in figuring out that `shift_tokens_right()` was the source of the problem! I think your proposal makes sense and I was able to verify that including your change fixes the problem with the export.

What do you think @michaelbenayoun? If there are no negative consequences with changing `shift_tokens_right()`, my suggestion is to ask @farzanehnakhaee70 to open a PR to fix the issue.

**Comment by michaelbenayoun** [comment] 2022-01-18 10:17
Hi @farzanehnakhaee70, @lewtun,
Great catch @farzanehnakhaee70 !!
I would say that if you have a working solution you can definitely open a PR!

**Comment by lewtun** [comment] 2022-01-18 11:02
Hi @farzanehnakhaee70 before we open a PR, can you please share your environment details by running the command `transformers-cli env` and copy-and-pasting its output here?

I'd like to know which version of transformers this affects, the type of OS etc

**Comment by lewtun** [comment] 2022-01-24 16:53
Thanks for sharing your environment @farzanehnakhaee70! 

I did a fresh install with 

```
pip install transformers[onnxruntime]==4.15
```

and find I am no longer able to reproduce the error (here's a [Colab notebook](https://colab.research.google.com/drive/1DZov6u3KOhoi2WE7K9quDKAjuYVRFDdn?usp=sharing) if you want to verify). This suggests that the error I saw (and possibly in your case too) is a symptom of a problematic environment.

Would you mind doing a fresh install or providing a Colab notebook that reproduces the error? I'd like to be certain that the error is reproducible before we make any changes to the `transformers` codebase. Thank you!

**Comment by farzanehnakhaee70** [comment] 2022-01-25 07:42
Sure.

**Comment by farzanehnakhaee70** [comment] 2022-01-29 15:15
Hi,
Really sorry for the late response.
Today I was going to test this model. However, during the test this error occurs!
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/transformers/onnx/__main__.py", line 22, in <module>
    from .features import FeaturesManager
  File "/usr/lib/python3.8/site-packages/transformers/onnx/features.py", line 71, in <module>
    class FeaturesManager:
  File "/usr/lib/python3.8/site-packages/transformers/onnx/features.py", line 273, in FeaturesManager
    def get_model_from_feature(feature: str, model: str) -> PreTrainedModel:
NameError: name 'PreTrainedModel' is not defined
```
Do you also face this issue?

**Comment by lewtun** [comment] 2022-01-31 21:15
Hi @farzanehnakhaee70 I am unfortunately not able to reproduce your error - by the looks of it, it could be a problem with your environment. Did you run a fresh install in a clean virtual env with the command I shared above?

**Comment by farzanehnakhaee70** [comment] 2022-02-01 07:13
Thanks for your reply @lewtun 
I install it inside a fresh container and also with the command you provided. I will test it once more and inform you about the incidence.

**Comment by farzanehnakhaee70** [comment] 2022-02-02 18:45
Hi @lewtun 
I test it once more with a fresh install. As you said, there isn't any problem. Thanks a lot for your consideration.

**Comment by lewtun** [comment] 2022-02-02 19:46
Thanks for double-checking @farzanehnakhaee70 ! Does this mean we can close this issue?

**Comment by farzanehnakhaee70** [comment] 2022-02-03 08:36
Hi @lewtun 
Thanks a lot. For sure.

**Closed** 2022-02-03 09:11 UTC
