### ISSUE TITLE
ImportError: cannot import name 'DataCollatorForLanguageModeling' in run_language_modeling.py

### ISSUE THREAD

**Issue by ishaansharma** [huggingface/transformers#3896] opened 2020-04-22 11:30 UTC
# 🐛 Bug ImportError: cannot import name 'DataCollatorForLanguageModeling' in run_language_modeling.py
## Information

> Traceback (most recent call last):
>   File "transformers/examples/run_language_modeling.py", line 29, in <module>
>     from transformers import (
> ImportError: cannot import name 'DataCollatorForLanguageModeling'

Model I am using (Bert, XLNet ...): roberta, Trying to build the model from scratch using the tutorial. 

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [x] the official example scripts: (give details below)
transformers/examples/run_language_modeling.py

* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)
My own Data set

## To reproduce

Follow the tutorial [here](https://huggingface.co/blog/how-to-train)

## Environment info

     
- `transformers` version: transformers-2.8.0 sacremoses-0.0.41 sentencepiece-0.1.85 tokenizers-0.5.2
- Platform:
- Python version: 3.x
- PyTorch version (GPU?):1.4.0
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: None

**Comment by julien-c** [comment] 2020-04-22 13:57
Duplicate of #3893 

Please install from source until we release a new version of the library on PyPI

**Closed by julien-c** 2020-04-22 13:57 UTC
