### ISSUE TITLE
Link for Absent Longformer Task Documentation

### ISSUE THREAD

**Issue by mert-kurttutan** [huggingface/transformers#22343] opened 2023-03-23 11:34 UTC
Hi,

I tried to look at the example tasks for Longformer. It lead to a page that does not exist and non-ideal response page.

How to reproduce:

1) Go to https://huggingface.co/docs/transformers/model_doc/longformer#documentation-resources
2) Click on any of the documentation resources, and arrive at the next page.

Maybe better notification saying these documentations dont exist yet would be better 

I guess this is more like a matter of how you present absent web pages.
![error_page](https://user-images.githubusercontent.com/88637659/227191372-4ce460bd-27f4-42de-9556-7b0b660f0d5b.png)
![error_page2](https://user-images.githubusercontent.com/88637659/227191418-b528ba58-b07b-4356-8f31-a15bb289f7b8.png)

**Comment by osanseviero** [comment] 2023-03-23 15:54
Transferred to transformers. As far as I can see, this is fixed in main and will work as intended in the next release. https://huggingface.co/docs/transformers/main/en/model_doc/longformer

**Comment by mert-kurttutan** [comment] 2023-03-23 16:03
Oh. Ok. Thanks.
It still seems weird that resources of this page are about generic task demonstration, not particularly related to Longformer
I guess this is a matter of design choice.
Feel free to close  this issue

**Closed** 2023-03-23 17:57 UTC
