### ISSUE TITLE
Feature Request: Fill Mask more than 1 token

### ISSUE THREAD

**Issue by p-christ** [huggingface/transformers#3619] opened 2020-04-03 14:49 UTC
At the moment you can use hugging face's mask filling pipeline to predict 1 masked token in a sentence using the below:

```
!pip install -q transformers
from __future__ import print_function
import ipywidgets as widgets
from transformers import pipeline

nlp_fill = pipeline('fill-mask')
nlp_fill("I am going to guess <mask> in this sentence")
```

The request is that you also add the ability to predict N masked tokens rather than only 1 masked token.  So that for example if the sentence is `"I am going to make <mask> <mask> for breakfast"` then the model might predict "fried eggs" for the 2 masked tokens

**Comment by julien-c** [comment] 2020-04-03 16:16
Duplicate of #3609 

Not currently supported but we welcome a PR

**Closed by julien-c** 2020-04-03 16:16 UTC
