### ISSUE TITLE
T5

### ISSUE THREAD

**Issue by ngoyal2707** [huggingface/transformers#1690] opened 2019-11-01 15:14 UTC
# 🌟New model addition

[Exploring the Limits of Transfer Learning with a
Unified Text-to-Text Transformer](https://arxiv.org/pdf/1910.10683.pdf)

## Open Source status

Code and model are open sourced

**Comment by LysandreJik** [comment] 2019-11-01 15:49
duplicate of #1617

**Closed by LysandreJik** 2019-11-01 15:49 UTC
