### ISSUE TITLE
when I encode [unused1], return not one token

### ISSUE THREAD

**Issue by jxyxiangyu** [huggingface/transformers#4683] opened 2020-05-30 07:44 UTC
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): bert

Language I am using the model on (English, Chinese ...): English

The problem arises when using: tokenizer.encode('[unused1]')
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:relation extraction
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. tokenizer.encode("[unused1]")
2. but return not one token, if using keras-bert, it will return me only one token
3.

## Environment info

     
- `transformers` version: least version
- Platform: 
- Python version: 3.7
- PyTorch version (GPU?):  1.1.0
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

**Comment by BramVanroy** [comment] 2020-05-30 09:57
I can reproduce this. cc @n1t0 @mfuntowicz Special "unused" tokens are not tokenised correctly. This happens in the fast tokenizers as well as the slow ones. See test case below.

```python
    from transformers import BertTokenizer
    USE_FAST = True

    tokenizer = BertTokenizer.from_pretrained("bert-base-cased", use_fast=USE_FAST)
    print('"[unused1]" in vocab?', "[unused1]" in tokenizer.vocab)
    print('"[unused1]" index in vocab', tokenizer.vocab["[unused1]"] if "[unused1]" in tokenizer.vocab else "NA")

    idxs = tokenizer.encode("[unused1]", add_special_tokens=False)
    print("indices", idxs)
    recoded = tokenizer.decode(idxs)
    print("recoded", recoded)
```

**Comment by mfuntowicz** [comment] 2020-06-02 07:45
Hi @jxyxiangyu, thanks for reporting this, thanks @BramVanroy to making a code to reproduce.

So far, the behavior you want to achieve needs to be done by deactivating the `do_basic_tokenize` feature on `BertTokenizer`, otherwise the input will be splitted on ponctuation chars before actually going through the wordpiece tokenizer.

_I don't think we have an equivalent on the Rust implementation of Bert, let me check internally and got back to you on this point._

Here a snippet of code which should achieve the desired behavior:

```python
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-cased", do_basic_tokenize=False)
tokenizer.tokenize("[unused1]")

>>> ['[unused1]']

tokenizer.encode("[unused1]", add_special_tokens=False)
>>> [1]

tokenizer.decode([1])
>>> '[unused1]'
```

**Comment by jxyxiangyu** [comment] 2020-06-02 08:23
Thanks for responding to my query. After I tried the method you gave, ‘[unused1]’ can indeed be tokenized correctly, but I want to use '[unused1]' to concatenate two words with little connection. In my opinion,  may I  set other words do_basic_tokenize as True, and '[unused1]' as False?

**Comment by n1t0** [comment] 2020-06-03 14:08
Hi @jxyxiangyu! Thank you @BramVanroy & @mfuntowicz for the help on this!

I think in this case the easiest way to handle this, is by adding the tokens you plan to use as special tokens. After all, that's what they are. They are not added by default since only a handful of them are actually used so you need to do it manually with
```python
tokenizer.add_special_tokens({ "additional_special_tokens": [ "[unused1]" ] })
```

Then, it should work for both fast and slow tokenizers:
```python
>>> from transformers import AutoTokenizer

>>> slow = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)
>>> fast = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=True)

>>> slow.add_special_tokens({ "additional_special_tokens": [ "[unused1]" ] })
>>> fast.add_special_tokens({ "additional_special_tokens": [ "[unused1]" ] })

>>> slow.encode("[unused1]", add_special_tokens=False)
[1]
>>> fast.encode("[unused1]", add_special_tokens=False)
[1]
```

**Comment by jxyxiangyu** [comment] 2020-06-03 14:13
Thank you very much for your response, which solved my confusion

**Comment by n1t0** [comment] 2020-06-04 02:58
Awesome! Closing the issue, do not hesitate to reopen if needed!

**Closed by n1t0** 2020-06-04 02:58 UTC
Labels: Core: Tokenization
