### ISSUE TITLE
Metas MMS speech recognition

### ISSUE THREAD

**Issue by LYPinASR** [huggingface/transformers#23811] opened 2023-05-27 08:36 UTC
### Feature request

Our request a simpler and more convenient inference process for a speech recognition model based on MMS just like wav2vec 2.0 in Transformers. 

### Motivation

We aim to encapsulate the various subroutines called by Facebook’s official model into a direct speech recognition model that is as easy to use as other transformer-based models like wav2vec 2.0. But we also know that the Hugging face team has been among the industry leaders in this area of work.

### Your contribution

We recognize that it may not be feasible for us to directly assist the Hugging Face technical team in this task. We believe that such an effort would be forward-looking given the popularity of MMS in current speech recognition research. The resulting model would be ideal for quickly transcribing our meeting notes.

**Comment by NielsRogge** [comment] 2023-05-27 08:37
Duplicate of #23665

**Comment by LYPinASR** [comment] 2023-05-27 12:32
@NielsRogge 
Hi, Can you tell me how far along we are and about how long it will be ready for us to use? Thank you!

**Closed** 2023-06-02 09:30 UTC

**Comment by patrickvonplaten** [comment] 2023-06-02 11:28
PR merged.

Also see:
- https://huggingface.co/docs/transformers/main/en/model_doc/mms
- https://github.com/huggingface/transformers/pull/23813
- https://huggingface.co/facebook/mms-1b-all

**Comment by darknight2163** [comment] 2023-07-20 10:05
> PR merged.
> 
> Also see:
> 
> * https://huggingface.co/docs/transformers/main/en/model_doc/mms
> * [[MMS] Scaling Speech Technology to 1,000+ Languages | Add attention adapter to Wav2Vec2 #23813](https://github.com/huggingface/transformers/pull/23813)
> * https://huggingface.co/facebook/mms-1b-all

Can I use my own dataset instead of the dataset "mozilla_foundation_common voice_6.1", which you have shown in tutorial [https://huggingface.co/blog/mms_adapters](url) ? If so then , how. Thanks

**Comment by patrickvonplaten** [comment] 2023-07-20 13:15
Sure, you just need to load your own dataset, maybe this helps: https://huggingface.co/docs/datasets/v2.13.1/en/audio_load

**Comment by darknight2163** [comment] 2023-07-23 19:13
> Sure, you just need to load your own dataset, maybe this helps: https://huggingface.co/docs/datasets/v2.13.1/en/audio_load
Thank you foe your kind reply, although I have gone through the suggested tutorial but it didn't help, and ...
I have just uploaded some demo dataset here u can check it: [https://huggingface.co/datasets/rashmi035/MKB_Hindi_2023](url) ,As you can see the audio is visible in the dataset viewer but the corresponding ngram is not visible, can you help me with this?
