### ISSUE TITLE
Different vocab_size between model and tokenizer of mT5

### ISSUE THREAD

**Issue by cih9088** [huggingface/transformers#10528] opened 2021-03-05 02:24 UTC
## Environment info

- `transformers` version: 4.1.1
- Platform: ubuntu 18.04
- Python version: 3.8.5
- PyTorch version (GPU?): 1.7.1
### Who can help
@patrickvonplaten

## To reproduce

```python
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer

mt5s = ['google/mt5-base', 'google/mt5-small', 'google/mt5-large', 'google/mt5-xl', 'google/mt5-xxl']

for mt5 in mt5s:
    model = AutoModelForSeq2SeqLM.from_pretrained(mt5)
    tokenizer = AutoTokenizer.from_pretrained(mt5)

    print()
    print(mt5)
    print(f"tokenizer vocab: {tokenizer.vocab_size}, model vocab: {model.config.vocab_size}")
```
This is problematic in case when one addes some (special) tokens to tokenizer and resizes the token embedding of the model with `model.resize_token_embedding(len(tokenizer))`

## Expected behavior
vocab_size for model and tokenizer should be the same?

**Comment by LysandreJik** [comment] 2021-03-05 02:29
Hello! This is a duplicate of https://github.com/huggingface/transformers/issues/4875, https://github.com/huggingface/transformers/issues/10144 and https://github.com/huggingface/transformers/issues/9247

@patrickvonplaten, maybe we could do something about this in the docs? In the docs we recommend doing this:
```py
model.resize_token_embedding(len(tokenizer))
```
but this is unfortunately false for T5!

**Comment by patrickvonplaten** [comment] 2021-03-05 07:21
@LysandreJik @cih9088 , actually I think doing: 

```python
model.resize_token_embedding(len(tokenizer))
```

is fine -> it shouldn't throw an error & logically it should also be correct...Can you try it out?

**Comment by cih9088** [comment] 2021-03-05 07:50
```python
model.resize_token_embedding(len(tokenizer))
```
This works perfectly fine but here is the thing.

One might add the `model.resize_token_embedding(len(tokenizer))` in their code and use other config packages such as `hydra` from Facebook to train models with additional tokens or without them.
He would naturally think that `vocab_size` of tokenizer (no tokens added) and `vocab_size` of model are the same because other models are.
Eventually, he fine-tunes the `google/mt5-base` model without added tokens but because of `model.resize_token_embedding(len(tokenizer))`, model he will fine-tune is not the same with `google/mt5-base`.
After training, he wants to load the trained model but the model complains about inconsistent embedding size between a loaded model which is `google/mt5-base`, and the trained model which has a smaller size of token embedding.

Of course, we could resize token embedding before loading model, but what matters is inconsistency with other models.
I reckon that people would not very much care about how the dictionary is composed in tokenizer. Maybe we add some dummy tokens to the tokenizer to keep consistency with other huggingface models or add documentation about it (I could not find any).

**Closed** 2021-04-23 15:02 UTC

**Comment by takiholadi** [comment] 2021-08-10 21:12
> Hello! This is a duplicate of #4875, #10144 and #9247
> 
> @patrickvonplaten, maybe we could do something about this in the docs? In the docs we recommend doing this:
> 
> ```python
> model.resize_token_embedding(len(tokenizer))
> ```
> 
> but this is unfortunately false for T5!

What is the correct way to resize_token_embedding for T5? It looks like there are 12 additional tokens and `model.resize_token_embedding(len(tokenizer) + 12)` works well.
