### ISSUE TITLE
Add error message to Wav2Vec2 & Hubert if labels > vocab_size

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#12270] opened 2021-06-20 10:49 UTC
# 🚀 Feature request

Add better error message to `HubertForCTC`, `Wav2Vec2ForCTC` if labels are bigger than vocab size.

## Motivation

Following this issue: https://github.com/huggingface/transformers/issues/12264 it is clear that an error message should be thrown if any of the any of the labels are > `self.config.vocab_size` or else silent errors can sneak into the training script.

So we should modify: `Wav2Vec2ForCTC`, `TFWav2Vec2ForCTC`, and `HubertForCTC` to add a nice error message in this case.

## Your contribution

This is a first good issue and should be rather easy to accomplish. I'm happy to give more guidance if needed.

**Comment by vasudevgupta7** [comment] 2021-06-20 13:00
I will create a PR to fix this.

**Comment by VirajBagal** [comment] 2021-09-18 14:52
@vasudevgupta7 @patrickvonplaten Is this fixed? If not, I will like to work on it.

**Comment by vasudevgupta7** [comment] 2021-09-18 14:57
Hey, this issue has been fixed in this PR: https://github.com/huggingface/transformers/pull/12288

**Comment by VirajBagal** [comment] 2021-09-18 15:20
Thanks for informing. I had seen it, but since the issue is still open, I thought something might be left.

**Comment by LysandreJik** [comment] 2021-09-20 16:26
Closing as fixed :)

**Closed by LysandreJik** 2021-09-20 16:26 UTC
Labels: Good First Issue
