### ISSUE TITLE
trainer save_model ValueError You are trying to save a non contiguous tensor

### ISSUE THREAD

**Issue by siebeniris** [huggingface/transformers#28293] opened 2023-12-31 22:26 UTC
### System Info

Transformers version: 4.36.2
pytorch version:  2.1.1
Python version: 3.10.13

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Fine-tuning mt5 model on a task using transformers trainer, and try to save the model, then the following error occurs. 
 
```
  File "/home/xxx/xxx/xxx/run.py", line 17, in main
    experiment.run()
  File "/home/xxx/xxx/xxx/experiments.py", line 162, in run
    self.train()
  File "/home/xxx/xxx/xxx/experiments.py", line 207, in train
    trainer.save_model()  # Saves the tokenizer too for easy upload
  File "/home/xxx/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2849, in save_model
    self._save(output_dir)
  File "/home/xxx/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2909, in _save
    self.model.save_pretrained(
  File "/home/xxx/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2376, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "/home/xxx/.local/lib/python3.10/site-packages/safetensors/torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/home/xxx/.local/lib/python3.10/site-packages/safetensors/torch.py", line 475, in _flatten
    return {
  File "/home/xxx/.local/lib/python3.10/site-packages/safetensors/torch.py", line 479, in <dictcomp>
    "data": _tobytes(v, k),
  File "/home/xxx/.local/lib/python3.10/site-packages/safetensors/torch.py", line 396, in _tobytes
    raise ValueError(
ValueError: You are trying to save a non contiguous tensor: `encoder_decoder.encoder.block.0.layer.0.SelfAttention.q.weight` which is not allowed. It either means you are trying to save tensors which are reference of each other in which case it's recommended to save only the full tensors, and reslice at load time, or simply call `.contiguous()` on your tensor to pack it before saving.
```

### Expected behavior

Fine-tune mt5 model, and try to save the fine-tuned model, it renders the above error, and modifying `transformers/modeling_utils.py` file with `state_dict= {k:v.contiguous() for k,v in state_dict.items()}` solves the problem.

**Comment by LysandreJik** [comment] 2024-01-11 15:27
hmmm do  you know what might be happening here @Narsil ? With mt5

**Comment by ArthurZucker** [comment] 2024-01-11 15:55
Might be fixed by #28414 ?

**Comment by Narsil** [comment] 2024-01-12 09:57
Happy to take a look if I can have acces either to the finetune (even dummy I just need to look at those tensors) or a reproducer.

I have no idea what makes some tensors non contiguous and what kind of non contiguous those are

**Comment by fxmarty** [comment] 2024-01-16 12:32
Non-contiguous tensors can be saved with `safe_serialization=False` but not with `safe_serialization=True`.

**Comment by Narsil** [comment] 2024-01-17 13:21
I was try to ask more, what lib is actually creating non contiguous tensors ? Seems odd to me that we need to create non contiguous tensors for training.

Deepspeed for isntant it's  not non contiguous it' s more that they abuse the storage system to force several matmul locality (which I think it to optimize network transport), therefore it was easy to fix once identified (because that's a condition where it's easy to rework the tensors on behalf of users since the non contiguity is not really important for the model).

**Comment by jaketae** [comment] 2024-01-26 19:23
I ran into this issue due to a custom weight tying scheme (output layer is a transpose of the vocabulary embedding, so the former is not contiguous). I got around the error by turning of safe serialization as noted above.

**Comment by siebeniris** [comment] 2024-02-02 12:47
Hi, thanks all for the comments. I have no idea why there are even non-contiguous tensors. I think make them contiguous makes more sense? And it solves the problem and the model training seems to be well. I found it odd that the error doesn't occur for trains T5 models, only for MT5 models, since MT5 is built upon T5 in transformers scripts.

**Comment by ArthurZucker** [comment] 2024-03-05 08:26
This is related to the PR that was reverted #28898 I believe!

**Closed** 2024-04-02 14:59 UTC

**Comment by ZhanGHanG9991** [comment] 2024-08-07 14:22
I also encounter this problem when I try to fine-tune google-t5/t5-base model.

System Info:
Transformers version: 4.43.4
pytorch version: 2.4.0
Python version: 3.8.19

**Comment by odunola499** [comment] 2024-08-12 17:33
This is crude but you can add this to your code just when you initialise your model. 
`for param in model.parameters():
    param.data = param.data.contiguous()`

**Comment by OrrZwebner** [comment] 2024-08-13 10:42
> @ZhanGHanG9991 This is crude but you can add this to your code just when you initialise your model. `for param in model.parameters(): param.data = param.data.contiguous()`

Amazing it work me! I add this in the __init__() just after the init of the model
(I used Byt5 model):
![image](https://github.com/user-attachments/assets/f8ffcd86-4c68-4f01-b744-dd737f2d405e)

**Comment by duanfa** [comment] 2024-09-25 00:45
> @ZhanGHanG9991 This is crude but you can add this to your code just when you initialise your model. `for param in model.parameters(): param.data = param.data.contiguous()`

It worked ! thanks

**Comment by ZhanGHanG9991** [comment] 2024-11-06 08:21
> @ZhanGHanG9991 This is crude but you can add this to your code just when you initialise your model. `for param in model.parameters(): param.data = param.data.contiguous()`

Thanks!!
