### ISSUE TITLE
IPEX integration in Trainer breaks with PyTorch 1.12

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#17962] opened 2022-06-30 13:55 UTC
All the tests for the IPEX integration in Trainer started to break with the latest PyTorch release. Error is:
```
ImportError: /usr/local/lib/python3.8/dist-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-cpu.so: undefined symbol: _ZNK3c1010TensorImpl5sizesEv
```

cc @hshen14

**Comment by hshen14** [comment] 2022-06-30 14:08
@sgugger Thanks for reporting. IPEX v1.12 will be releasing to support latest PyTorch version by next week. The team will look into the issue and let you know whether the issue is getting fixed in upcoming release. cc @jianan-gu

**Comment by EikanWang** [comment] 2022-06-30 23:03
@sgugger , this is Eikan from IPEX team. This is a version-mismatch issue. IPEX 1.11 is on top of PyTorch 1.11. And the upcoming release of IPEX(1.12) will resolve this issue as the latest PyTorch is 1.12. I will keep you posted as long as the IPEX is released.

**Comment by jianan-gu** [comment] 2022-07-08 09:41
Hi @sgugger,
IPEX 1.12 release is available https://intel.github.io/intel-extension-for-pytorch/1.12.0/tutorials/installation.html ;
And we also open a PR https://github.com/huggingface/transformers/pull/18072 to enhance the for this version mismatch issue to avoid breaking Trainer;
Thanks!

**Closed** 2022-07-12 04:34 UTC
