### ISSUE TITLE
Link is broken in Huggingface model zoo

### ISSUE THREAD

**Issue by Embedding** [huggingface/transformers#13770] opened 2021-09-28 06:06 UTC
https://huggingface.co/google/bert_uncased_L-2_H-128_A-2

![image](https://user-images.githubusercontent.com/31317254/135032197-876f5513-bbae-4e14-9e9c-8d1f8ad9515c.png)

The link is broken for a long time which is very inconvenient for users. It would be very helpful if you can fix this bug.

**Comment by julien-c** [comment] 2021-09-28 07:10
for @elishowk :)

**Comment by elishowk** [comment] 2021-09-28 07:32
Hi, thanks for reporting, it's a duplicate of https://github.com/huggingface/transformers/issues/13558
Do you mind if I close it and tag you on the other issue ?

**Closed** 2021-09-28 08:01 UTC
