### ISSUE TITLE
Unable to reproduce the simple code snippets in official doc for google/gemma-7b

### ISSUE THREAD

**Issue by WadeYin9712** [huggingface/transformers#29181] opened 2024-02-21 19:45 UTC
### System Info

- `transformers` version: 4.39.0.dev0
- Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.0 (True)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer, GemmaForCausalLM

model = GemmaForCausalLM.from_pretrained("google/gemma-7b")
tokenizer = AutoTokenizer.from_pretrained("google/gemma-7b")

prompt = "What is your favorite condiment?"
inputs = tokenizer(prompt, return_tensors="pt")

generate_ids = model.generate(inputs.input_ids, max_length=30)
tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
```

Then it will report a bug like this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/nfs/mosaic/day/envs/opensource/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/day/transformers/src/transformers/generation/utils.py", line 1549, in generate
    result = self.greedy_search(
  File "/home/day/transformers/src/transformers/generation/utils.py", line 2420, in greedy_search
    outputs = self(
  File "/net/nfs/mosaic/day/envs/opensource/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/day/transformers/src/transformers/models/gemma/modeling_gemma.py", line 1062, in forward
    outputs = self.model(
  File "/net/nfs/mosaic/day/envs/opensource/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/day/transformers/src/transformers/models/gemma/modeling_gemma.py", line 904, in forward
    layer_outputs = decoder_layer(
  File "/net/nfs/mosaic/day/envs/opensource/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/day/transformers/src/transformers/models/gemma/modeling_gemma.py", line 624, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/net/nfs/mosaic/day/envs/opensource/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/day/transformers/src/transformers/models/gemma/modeling_gemma.py", line 279, in forward
    attn_output = attn_output.reshape(bsz, q_len, self.hidden_size)
RuntimeError: shape '[1, 8, 3072]' is invalid for input of size 32768
```

### Expected behavior

Hi Hf! I encountered a problem about shape misalignment when I use the official code example to test the google/gemma-7b model. Would appreciate a lot if you could offer some help to fix this issue! I'm using the library built from the latest source code.

**Comment by amyeroberts** [comment] 2024-02-21 21:42
Cc @ArthurZucker @younesbelkada

**Comment by arnavgarg1** [comment] 2024-02-21 22:20
Can confirm that I'm running into the same error! I've tried the following:
- Using Transformers 4.38.0
- Using Transformers master
- Fine-tuning with PEFT and without PEFT

**Comment by alisafaya** [comment] 2024-02-21 22:50
Yes, it solves the problem. But the prediction values do not seem to be
correct.

**Comment by arnavgarg1** [comment] 2024-02-21 23:00
Thanks for the heads up @WadeYin9712! 

@alisafaya Out of curiosity, what is the issue with the prediction values?

**Comment by ArthurZucker** [comment] 2024-02-22 01:59
This was fixed on main!

**Comment by arnavgarg1** [comment] 2024-02-22 02:18
@ArthurZucker I just tried the main branch and I'm still running into the same issue. Here's a minimal repro script:

```python
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "google/gemma-7b-it"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.float16, attn_implementation="eager")

# Define a prompt for text generation
prompt = "Once upon a time, "
input_ids = tokenizer.encode(prompt, return_tensors="pt")

# Generate text
max_length = 50
output = model.generate(input_ids, max_length=max_length)
```

**Comment by arnavgarg1** [comment] 2024-02-22 02:29
What's interesting here is that `google/gemma-2b-it` works fine with this exact same script I shared. So it seems to be specific to `google/gemma-7b` and `google/gemma-7b-it`.

**Comment by ArthurZucker** [comment] 2024-02-22 02:37
<img width="1800" alt="image" src="https://github.com/huggingface/transformers/assets/48595927/1a295308-f12e-47e5-a9c3-444f9090c5d5">
Sorry I cannot reproduce this on the release branch, nor on main.

**Comment by ArthurZucker** [comment] 2024-02-22 02:37
```python 

In [2]: model
Out[2]: 
GemmaForCausalLM(
  (model): GemmaModel(
    (embed_tokens): Embedding(256000, 3072, padding_idx=0)
    (layers): ModuleList(
      (0-27): 28 x GemmaDecoderLayer(
        (self_attn): GemmaAttention(
          (q_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (k_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (v_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
          (rotary_emb): GemmaRotaryEmbedding()
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=3072, out_features=24576, bias=False)
          (up_proj): Linear(in_features=3072, out_features=24576, bias=False)
          (down_proj): Linear(in_features=24576, out_features=3072, bias=False)
          (act_fn): GELUActivation()
        )
        (input_layernorm): GemmaRMSNorm()
        (post_attention_layernorm): GemmaRMSNorm()
      )
    )
    (norm): GemmaRMSNorm()
  )
  (lm_head): Linear(in_features=3072, out_features=256000, bias=False)
)
```
double checked that I am using `eager`

**Comment by arnavgarg1** [comment] 2024-02-22 02:46
@ArthurZucker thanks for running it and confirming! What Torch version are you using?

**Comment by ArthurZucker** [comment] 2024-02-22 02:48
It is not related to the torch version. 
If the traceback is: 
```python 
  File "/home/ray/anaconda3/lib/python3.8/site-packages/transformers/models/gemma/modeling_gemma.py", line 279, in forward
    attn_output = attn_output.reshape(bsz, q_len, self.hidden_size)
RuntimeError: shape '[1, 49, 3072]' is invalid for input of size 200704
```
then you have the wrong version of `transformers`, 
Because we shipped: 
```diff
- attn_output = attn_output.reshape(bsz, q_len, self.hidden_size)
+ attn_output = attn_output.reshape(bsz, q_len, -1)
```

**Comment by ArthurZucker** [comment] 2024-02-22 03:00
🤗 no worries sorry for the confusion, we should have caught this!

**Comment by arnavgarg1** [comment] 2024-02-22 03:01
@ArthurZucker No worries, thanks for your help!

**Comment by alisafaya** [comment] 2024-02-23 15:31
Reopening.

This issue is still not solved: The perplexity values of gemma-2b and gemma-7b (much worse, near random) are very different. Wikitext-v2 token perplexity for gemma-2b ~= 21. For gemma-7b it is a very large value ~= 1e13.

**Comment by younesbelkada** [comment] 2024-02-27 02:14
@alisafaya , interesting ! can you share how do you compute the perplexity for these models?

**Comment by ArthurZucker** [comment] 2024-02-27 05:48
Let's close this issue it's not related to the reported bug.

**Closed by ArthurZucker** 2024-02-27 05:48 UTC

**Comment by alisafaya** [comment] 2024-02-27 09:47
> @alisafaya , interesting ! can you share how do you compute the perplexity for these models?
@younesbelkada here are my findings on this: https://github.com/huggingface/transformers/issues/29250#issuecomment-1966149282
