### ISSUE TITLE
RuntimeError: expected device cpu but got device cuda:0

### ISSUE THREAD

**Issue by zaowad** [huggingface/transformers#4240] opened 2020-05-08 18:44 UTC
I am traing a roberta model and running the script examples/run_language_modeling.py
The following error occurs when i am trying to resume training.
Traceback (most recent call last):
  File "examples/run_language_modeling.py", line 284, in <module>
    main()
  File "examples/run_language_modeling.py", line 254, in main
    trainer.train(model_path=model_path)
  File "/home/socian-pc1/anaconda3/envs/XformerEnv/lib/python3.6/site-packages/transformers/trainer.py", line 326, in train
    optimizer.step()
  File "/home/socian-pc1/anaconda3/envs/XformerEnv/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/socian-pc1/anaconda3/envs/XformerEnv/lib/python3.6/site-packages/transformers/optimization.py", line 155, in step
    exp_avg.mul_(beta1).add_(1.0 - beta1, grad)
RuntimeError: expected device cpu but got device cuda:0

My config
python examples/run_language_modeling.py \
    --train_data_file $TRAIN_FILE \
    --eval_data_file $TEST_FILE \
    --output_dir ./MyRobertaOutput \
    --model_name_or_path ./MyRoBERTa/checkpoint-570000 \
    --config_name ../xformer_output \
    --tokenizer_name ../xformer_output \
    --mlm \
    --do_train \
    --do_eval \
    --line_by_line \
    --learning_rate 1e-5 \
    --num_train_epochs 2 \
    --save_total_limit 20 \
    --save_steps 5000 \
    --per_gpu_train_batch_size 6 \
    --warmup_steps=10000 \
    --logging_steps=100 \
    --gradient_accumulation_steps=4 \
    --seed 666 --block_size=512

**Comment by tebandesade** [comment] 2020-05-09 00:08
Try changing the optimization script and modify exp_avg and exp_avg_sq to be .cuda()

**Comment by tebandesade** [comment] 2020-05-09 00:51
Try initialize the model in the trainer script from transformers with self.model = model.cuda()

**Comment by octalpixel** [comment] 2020-05-15 02:43
I am getting the same error. Is there work around ? 
What @tebandesade  mentioned didnt work out for.

**Comment by bokertof** [comment] 2020-05-15 11:53
I faced the same problem with RoBERTa pretraining, however inserting line model = model.cuda() before trainer in run_language_modeling.py file helped me
@tebandesade, Thank you!

**Comment by LysandreJik** [comment] 2020-05-15 13:37
Hello! I'm having trouble reproducing that on master. Do you mind installing from source and letting me know if you still have the issue? Thank you

**Comment by pranavpawar3** [comment] 2020-05-15 20:39
Hi @LysandreJik, installing from source doesn't fix the issue, though @tebandesade's suggestion works fine. 

@octalpixel try editing this line, it shall work;
https://github.com/huggingface/transformers/blob/62427d0815825436fa55b43725f44776e94abb65/src/transformers/trainer.py#L145

**Comment by shaoyent** [comment] 2020-05-16 19:22
I am getting this error too.

I think the issue is optimizers are [setup](https://github.com/huggingface/transformers/blob/3e0f06210646a440509efa718b30d18322d6a830/src/transformers/trainer.py#L242) from `self.model` which is in cpu, but the model is [moved to device](https://github.com/huggingface/transformers/blob/3e0f06210646a440509efa718b30d18322d6a830/src/transformers/trainer.py#L338) afterwards. Which is why `self.model = model.cuda()` fixes the error.

**Comment by julien-c** [comment] 2020-05-19 03:14
Should be fixed on master thanks to @shaoyent . Give it a try and let us know:)

**Closed** 2020-05-19 03:13 UTC

**Comment by mcggood** [comment] 2020-05-23 15:49
> I am getting this error too.
> 
> I think the issue is optimizers are [setup](https://github.com/huggingface/transformers/blob/3e0f06210646a440509efa718b30d18322d6a830/src/transformers/trainer.py#L242) from `self.model` which is in cpu, but the model is [moved to device](https://github.com/huggingface/transformers/blob/3e0f06210646a440509efa718b30d18322d6a830/src/transformers/trainer.py#L338) afterwards. Which is why `self.model = model.cuda()` fixes the error.

It works if you didn't install transformers package, or you will need to modify the installed package file.
