### ISSUE TITLE
"Xformers is not installed correctly." error

### ISSUE THREAD

**Issue by engageintellect** [huggingface/transformers#25604] opened 2023-08-18 19:09 UTC
### System Info

System info:
* Transformers 4.31.0
* Python 3.11.3

Error:
```
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
```

Code:
```
import argparse
from transformers import pipeline

# Create the parser
parser = argparse.ArgumentParser(description="Perform sentiment analysis")

# Add an argument
parser.add_argument('Text', type=str, help="the text to analyze")

# Parse the argument
args = parser.parse_args()

# Load the classifier
classifier = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

# Perform sentiment analysis
res = classifier(args.Text)

# Print the result
print(res)
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to reproduce this behavior:
1. run my code
2. receive error

### Expected behavior

no error

**Comment by sgugger** [comment] 2023-08-18 21:15
This is a duplicate of #24903

**Closed by sgugger** 2023-08-18 21:15 UTC
