### ISSUE TITLE
codellama/CodeLlama-34b Fine-Tune Evaluation 

### ISSUE THREAD

**Issue by sanipanwala** [huggingface/transformers#28815] opened 2024-02-01 10:01 UTC
Hello,

I have done training and saved the model, and adapter config file on the local disk.

When I load the model from the local disk again to generate the output I get the below error.

Anyone can help me with this issue?

`File "PythonV2.py", line 11, in <module> model = AutoPeftModelForCausalLM.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/python3.12/site-packages/peft/auto.py", line 127, in from_pretrained return cls._target_peft_class.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/python3.12/site-packages/peft/peft_model.py", line 354, in from_pretrained model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs) File "/python3.12/site-packages/peft/peft_model.py", line 695, in load_adapter adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/python3.12/site-packages/peft/utils/save_and_load.py", line 313, in load_peft_weights adapters_weights = safe_load_file(filename, device=device) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/python3.12/site-packages/safetensors/torch.py", line 308, in load_file with safe_open(filename, framework="pt", device=device) as f: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization `

Thanks.

**Comment by ArthurZucker** [comment] 2024-02-01 13:18
cc @younesbelkada safetensors + peft

**Comment by younesbelkada** [comment] 2024-02-02 01:28
hi @sanipanwala 
do you face the same issue when you update `peft` and `safetensors` ? `pip install -U peft safetensors`

**Comment by sanipanwala** [comment] 2024-02-02 03:24
@younesbelkada ,

Yes, I have created a fresh conda environment and installed all the latest packages.

Thanks,

**Comment by younesbelkada** [comment] 2024-02-02 03:30
Have you used torch.compile by any chance? It seems to be a duplicate of https://github.com/huggingface/transformers/issues/27397

**Comment by sanipanwala** [comment] 2024-02-02 04:10
Hi @younesbelkada ,

I just added torch.compile before trainer.train() It gives me the below exception.

```
    raise RuntimeError("Dynamo is not supported on Python 3.12+")
RuntimeError: Dynamo is not supported on Python 3.12+
```

Thanks.

**Closed** 2024-03-11 08:04 UTC
