### ISSUE TITLE
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by candowu** [huggingface/transformers#22222] opened 2023-03-17 07:23 UTC
### System Info

4.27.1

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

i test llama in colab here is my code and output:

!pip install git+https://github.com/huggingface/transformers
!pip install sentencepiece

import torch
from transformers import pipeline,LlamaTokenizer,LlamaForCausalLM

device = "cuda:0" if torch.cuda.is_available() else "cpu"
print(device)

# tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf")
# model = LlamaForCausalLM.from_pretrained("decapoda-research/llama-7b-hf")
generator = pipeline(model="decapoda-research/llama-7b-hf", device=device)
generator("I can't believe you did such a ")

ValueError                                Traceback (most recent call last)
[<ipython-input-3-c1d71e177e5a>](https://localhost:8080/#) in <module>
      7 # tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf")
      8 # model = LlamaForCausalLM.from_pretrained("decapoda-research/llama-7b-hf")
----> 9 generator = pipeline(model="decapoda-research/llama-7b-hf", device=device)
     10 generator("I can't believe you did such a ")

1 frames
[/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    675 
    676             if tokenizer_class is None:
--> 677                 raise ValueError(
    678                     f"Tokenizer class {tokenizer_class_candidate} does not exist or is not currently imported."
    679                 )

ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

### Expected behavior

expect output generated info

**Comment by yhifny** [comment] 2023-03-17 08:43
I face the same issue

**Comment by amyeroberts** [comment] 2023-03-17 08:48
Hi @candowu, thanks for raising this issue. This is arising, because the `tokenizer` in the [config on the hub](https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/tokenizer_config.json) points to `LLaMATokenizer`. However, the tokenizer in the library is `LlamaTokenizer`. 

This is likely due to the configuration files being created before the final PR was merged in.

**Comment by yhifny** [comment] 2023-03-17 09:45
I cloned the repo and changed the tokenizer in the config file to LlamaTokenizer 
but I got
ValueError: Tokenizer class LlamaTokenizer does not exist or is not currently imported.

**Comment by mbehm** [comment] 2023-03-17 10:17
For anybody interested I was able to load an earlier saved model with the same issue using my [fork](https://github.com/mbehm/transformers) with the capitalization restored. That being said for future it's probably better to try find or save a new model with the new naming.

**Comment by svigx** [comment] 2023-03-17 17:11
Thanks guys, i just had to install pip install git+https://github.com/huggingface/transformers and it worked

**Comment by nadahlberg** [comment] 2023-03-17 18:56
I can import the `LlamaTokenizer` class, but getting error that `from_pretrained` method is None.  Anyone else having this issue?

**Comment by sgugger** [comment] 2023-03-17 19:09
As the error message probably mentions, you need to install sentencepiece: `pip install sentencepiece`.

**Comment by nadahlberg** [comment] 2023-03-17 19:23
Working now. I swear I had sentencepiece, but probably forgot to reset the runtime 🤦  My bad!

**Comment by xhinker** [comment] 2023-03-17 22:31
> For anybody interested I was able to load an earlier saved model with the same issue using my [fork](https://github.com/mbehm/transformers) with the capitalization restored. That being said for future it's probably better to try find or save a new model with the new naming.

Thanks, man, your link solved all the problem

**Closed** 2023-03-17 22:54 UTC

**Comment by nameless0704** [comment] 2023-03-21 01:50
> Hi @candowu, thanks for raising this issue. This is arising, because the `tokenizer` in the [config on the hub](https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/tokenizer_config.json) points to `LLaMATokenizer`. However, the tokenizer in the library is `LlamaTokenizer`.
> 
> This is likely due to the configuration files being created before the final PR was merged in.

Change the **LLaMATokenizer** in tokenizer_config.json into lowercase **LlamaTokenizer** and it works like a charm.

**Comment by vdattwani2005** [comment] 2023-03-26 05:58
> For anybody interested I was able to load an earlier saved model with the same issue using my [fork](https://github.com/mbehm/transformers) with the capitalization restored. That being said for future it's probably better to try find or save a new model with the new naming.

Thank you so much for this! Works!

**Comment by israa04** [comment] 2023-03-29 13:08
> > Hi @candowu, thanks for raising this issue. This is arising, because the `tokenizer` in the [config on the hub](https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/tokenizer_config.json) points to `LLaMATokenizer`. However, the tokenizer in the library is `LlamaTokenizer`.
> > This is likely due to the configuration files being created before the final PR was merged in.
> 
> Change the **LLaMATokenizer** in tokenizer_config.json into lowercase **LlamaTokenizer** and it works like a charm.

I assume this is applied to the llama-7b cloned repo from HuggingFace right? How can I instantiate the model and the tokenizer after doing that please?

**Comment by thekevshow** [comment] 2023-03-30 05:42
> 

you are a life saver. There docs on the site should be updated for this reference.

**Comment by RiseInRose** [comment] 2023-03-31 06:02
> > > Hi @candowu, thanks for raising this issue. This is arising, because the `tokenizer` in the [config on the hub](https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/tokenizer_config.json) points to `LLaMATokenizer`. However, the tokenizer in the library is `LlamaTokenizer`.
> > > This is likely due to the configuration files being created before the final PR was merged in.
> > 
> > 
> > Change the **LLaMATokenizer** in tokenizer_config.json into lowercase **LlamaTokenizer** and it works like a charm.
> 
> I assume this is applied to the llama-7b cloned repo from HuggingFace right? How can I instantiate the model and the tokenizer after doing that please?

Thank you so much for this! Works!

**Comment by RiseInRose** [comment] 2023-03-31 06:12
Thank you so much for this! Works! That's amazing!

**Comment by alvations** [comment] 2023-04-02 01:54
You can try this for a ather crazy way to find out what is the right casing for the module:

```python
import transformers

from itertools import product
import importlib

def find_variable_case(s, max_tries=1000):
  var_permutations = list(map("".join, product(*zip(s.upper(), s.lower()))))
  # Intuitively, any camel casing should minimize the no. of upper chars.
  # From https://stackoverflow.com/a/58789587/610569
  var_permutations.sort(key=lambda ss: (sum(map(str.isupper, ss)), len(ss)))
  for i, v in enumerate(var_permutations):
    if i > max_tries:
      return
    try:
      dir(transformers).index(v)
      return v
    except:
      continue


v = find_variable_case('LLaMatokenizer')
exec(f"from transformers import {v}")
vars()[v]
```

**Comment by FatCache** [comment] 2023-04-02 22:14
I encountered the same issue identified at the thread today 4/2/2023. The post https://github.com/huggingface/transformers/issues/22222#issuecomment-1477171703 fixed the problem for me. 

Thank you.

**Comment by sgugger** [comment] 2023-04-12 11:39
You need to install the library from source to be able to use the LLaMA model.

**Comment by qufy6** [comment] 2023-04-12 12:18
> You need to install the library from source to be able to use the LLaMA model.

Thanks! Where can I get it? And how to install it? 
Actually I have already installed transformers 4.28.0.dev0, I'm not sure about what you mean.

**Comment by sgugger** [comment] 2023-04-12 12:46
You can open the documentation at the [install page](https://huggingface.co/docs/transformers/installation#install-from-source).

**Comment by thibaudart** [comment] 2023-04-18 10:13
Hi

I installed from source 

git clone https://github.com/huggingface/transformers.git
cd transformers
pip install -e .


 pip list show:

transformers       4.29.0.dev0 D:\myfolder\transformers

but I still have

ValueError: Tokenizer class LlamaTokenizer  does not exist or is not currently imported.

**Comment by mehrdadh** [comment] 2023-04-19 20:25
+1 on @thibaudart comment, I have the same issue.

**Comment by yeserumo** [comment] 2023-04-21 07:02
> Hi
> 
> I installed from source
> 
> git clone https://github.com/huggingface/transformers.git cd transformers pip install -e .
> 
> pip list show:
> 
> transformers 4.29.0.dev0 D:\myfolder\transformers
> 
> but I still have
> 
> ValueError: Tokenizer class LlamaTokenizer does not exist or is not currently imported.

hey, try this rep `pip install git+https://github.com/mbehm/transformers`, maybe it can work

**Comment by zhiyixu** [comment] 2023-05-04 09:19
@MasterLivens  hi, i am currently using colab, which file should i add this code?

**Comment by owanr** [comment] 2023-05-06 19:44
@zhiyixu The code being referred to should go into .../site-packages/transformers/models/auto/tokenization_auto.py

However, what worked for me was updating my transformers and tokenizers package. 
tokenization_auto.py has a mapping of tokenizers at the beginning and I realized that llama wasn't included in the version I had.

**Comment by zhanghanghitomi** [comment] 2023-06-13 05:58
Hi, @nameless0704. I am fairly new in this area. May I ask how to Change the LLaMATokenizer in tokenizer_config.json into lowercase LlamaTokenizer? Could not figure it out. 

Any information is appreciated. Thank you very much in advance!

**Comment by SupritYoung** [comment] 2023-06-13 08:40
I share a experiment, Just replace your llama model to https://huggingface.co/elinas/llama-7b-hf-transformers-4.29 will solve the error like ImportError: cannot import name 'LLaMATokenizer' from 'transformers'

**Comment by MasterLivens** [comment] 2023-06-27 01:26
> @MasterLivens hi, i am currently using colab, which file should i add this code?

the specified error file in the error message.

**Comment by AkshayVerma26** [comment] 2023-06-29 08:49
> > Hi @candowu, thanks for raising this issue. This is arising, because the `tokenizer` in the [config on the hub](https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/tokenizer_config.json) points to `LLaMATokenizer`. However, the tokenizer in the library is `LlamaTokenizer`.
> > This is likely due to the configuration files being created before the final PR was merged in.
> 
> Change the **LLaMATokenizer** in tokenizer_config.json into lowercase **LlamaTokenizer** and it works like a charm.

Where is the tokenizer_config.json?

**Comment by sifei** [comment] 2023-07-07 07:05
> > > Hi @candowu, thanks for raising this issue. This is arising, because the `tokenizer` in the [config on the hub](https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/tokenizer_config.json) points to `LLaMATokenizer`. However, the tokenizer in the library is `LlamaTokenizer`.
> > > This is likely due to the configuration files being created before the final PR was merged in.
> > 
> > 
> > Change the **LLaMATokenizer** in tokenizer_config.json into lowercase **LlamaTokenizer** and it works like a charm.
> 
> Where is the tokenizer_config.json?

I think this is the location:
.cache/huggingface/hub/models--decapoda-research--llama-65b-hf/snapshots/47d2b93e8c0a3d5d6582bdec13f233ca0527499a/tokenizer_config.json

**Comment by SanjayKotabagi** [comment] 2023-07-20 17:33
Please. Im facing the same issue. Can anyone help ? I tried all the above methods.

**Comment by PawelFaron** [comment] 2023-07-21 11:43
> Please. Im facing the same issue. Can anyone help ? I tried all the above methods.

I had the same issue and it was solved by:
pip uninstall transformers
pip install transformers

**Comment by Nayahei** [comment] 2023-07-26 09:05
in my code, transformer==4.30.0 can fix it

**Comment by calam1** [comment] 2023-07-26 19:58
```
 (
                "llama",
                (
                    "LlamaTokenizer" if is_sentencepiece_available() else None,
                    "LlamaTokenizerFast" if is_tokenizers_available() else None,
                ),
            ),
```
I had to install `sentencepiece` to bypass the not found error, running into other errors though :)

**Comment by selvaebi** [comment] 2023-07-28 09:33
> LlamaTokenizer

i changed it and referenced in tokenizer = AutoTokenizer.from_pretrained(model_path, tokenizer_config_file="/path/tokenizer_config.json") still same issue :(

**Comment by alexovai** [comment] 2023-08-16 03:25
I had similar issues. root cause was that I was using python3.7 where pip install transformers was older version 4.18. Once I upgraded to python3.9 pip3 install transformers install 4.30.0

Also make sure you have recent cuda drivers, running only on CPU was very slow for me.

**Comment by youshikyou** [comment] 2023-08-23 20:18
Hi, I still have the error. The letters are small letters but it still happens
![Screenshot 2023-08-23 at 22 15 25](https://github.com/huggingface/transformers/assets/35782965/6a492878-0f25-488b-8083-e9ff09116d2e)

**Comment by ndvbd** [comment] 2023-09-02 11:06
Do we need to load the tokenizer using LlamaTokenizer or can we use it with AutoTokenizer? If the latter is possible, what is the fully qualified tokenizer model on the hub?

**Comment by PGTBoos** [comment] 2023-09-18 18:47
same error on model codellama/CodeLlama-13b-hf
can onyone post a valid json config here ?

**Comment by ArthurZucker** [comment] 2023-09-18 22:42
No, the json is valid, you are just not working on `main` or at least the release that included `CodeLlamaTokenizer`... (https://github.com/huggingface/transformers/releases/tag/v4.33.1)

**Comment by dhruvsinha** [comment] 2023-09-25 14:44
I got the same error. I read that we have to edit 'tokenizer_config.json'. I did that on huggingface by changing the json file available in 'Files and versions' of the 'decapoda-research/llama-7b-hf', but I am not sure how to use the edited changes. This is my code:

`import torch
import transformers
from transformers import AutoTokenizer
from  langchain import LLMChain, HuggingFacePipeline, PromptTemplate

print("Import Complete")

model = "meta-llama/Llama-2-7b-hf
access_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
tokenizer = AutoTokenizer.from_pretrained(model, use_auth_token=access_token)`

I get the same error- ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

**Comment by ArthurZucker** [comment] 2023-09-26 15:30
You should use `model = "path/to/your/decapoda/modifided/model`

**Comment by k3ybladewielder** [comment] 2024-02-24 16:24
Any solution to this error ```ValueError: Tokenizer class LlamaTokenizer does not exist or is not currently imported.
``` ?

**Comment by mahsan-py** [comment] 2024-02-26 12:39
Install this library
pip install -U transformers

**Comment by James4Ever0** [comment] 2025-08-08 13:58
I use this hack when loading tokenizer for [BigTranslate](https://hf-mirror.com/James-WYang/BigTranslate). Though loaded, it does not guarantee to work with model inference and training.

The [discussion](https://hf-mirror.com/James-WYang/BigTranslate/discussions/1) suggests I should use [the original codebase](https://github.com/ZNLP/BigTrans/tree/main/model/) for loading the tokenizer "LLaMATokenizer".

```python
import transformers
setattr(transformers, "LLaMATokenizer", transformers.LlamaTokenizer)
tokenizer = transformers.AutoTokenizer("/James-WYang/BigTranslate")
```

You can compare the tokenizers between [BigTranslate](https://github.com/ZNLP/BigTranslate/blob/main/model/llama/tokenization_llama.py) and [huggingface/transformers](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/tokenization_llama.py). I think they are basically the same.
