### ISSUE TITLE
Llama inference instability in fp16 producing inf in the middle of the model

### ISSUE THREAD

**Issue by fxmarty** [huggingface/transformers#27179] opened 2023-10-31 14:05 UTC
### System Info

- `transformers` version: 4.35.0.dev0
- Platform: Linux-5.15.0-1023-aws-x86_64-with-glibc2.31
- Python version: 3.9.16
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.3.1
- Accelerate version: 0.25.0.dev0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Using GPU in script?: A100

### Who can help?

@ydshieh @fxmarty @gante

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi, I encounter inference instability with llama running in fp16 when left padding is used, and especially when full rows are masked out in the 4D attention mask.

At some point in the forward, `inf` values may appear in the intermediate logits, ultimately leading to tensors filled with `nan` and raising the error:

```
Traceback (most recent call last):
  File "=debug.py", line 38, in <module>
    outputs = model.generate(
  File "/fsx/felix/condaenvs/fx/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/fsx/felix/transformers/src/transformers/generation/utils.py", line 1704, in generate
    return self.sample(
  File "/fsx/felix/transformers/src/transformers/generation/utils.py", line 2822, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

Note that the `inf` specifically appear at a padding position.

Reproduction:

```python
from transformers import AutoTokenizer, pipeline, logging, AutoModelForCausalLM
import torch

model_name_or_path = "meta-llama/Llama-2-7b-chat-hf"
token = "[specify your token]"

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, use_fast=True, token=token)
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side = "left"

with torch.device("cuda"):
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, torch_dtype=torch.float16, token=token)

sentence = "Felix Marty is a French"

# Alternatively, the issue can be reproduced with:
# sentence = "Elon Musk is a South"
# max_length=9

inp = tokenizer(sentence, return_tensors='pt', padding="max_length", max_length=9).to("cuda")

print("inp", inp["input_ids"].shape)
print("inp", inp)
torch.set_printoptions(threshold=10000000)

print("\n\n*** Generate:")
with torch.no_grad():
    outputs = model.generate(
        **inp,
        max_new_tokens=10,
        do_sample=True,
        top_p=0.9,
        temperature=float(0.01),
        top_k=40
    )

print(tokenizer.batch_decode(outputs))
```

Printing `torch.all(torch.isfinite())` at some points in the model, it appears the `inf` start to appear in the MLP at [`self.gate_proj(x)) * self.up_proj(x)`](https://github.com/huggingface/transformers/blob/3cd3eaf96048cb76e67a432e72a7cecbdd1630a8/src/transformers/models/llama/modeling_llama.py#L232) and things go crazy from there.

What's interesting is that for example fixing (two left padding tokens)
![image](https://github.com/huggingface/transformers/assets/9808326/57474cd8-dc0a-4d46-9e9e-713e3b827902)

to

![image](https://github.com/huggingface/transformers/assets/9808326/0df5358a-c4b2-4e70-80d3-8e12fda0fc67)

solves the issue.

It makes me think that the solution implemented for SDPA to avoid fully masked rows in the attention mask may actually be required for some other cases as this one https://github.com/huggingface/transformers/pull/26572 - but it is unclear why it relates to overflow here.

WDYT @gante @ydshieh? Is this something you have ever observed?

### Expected behavior

No `inf` spawning in the middle of inference with fp16 model

**Comment by ydshieh** [comment] 2023-10-31 14:43
Related to #17937 but there is dummy model.

Will take a look here.

**Comment by gante** [comment] 2023-10-31 14:55
@ArthurZucker has been tracking it, and has a draft PR for it: https://github.com/huggingface/transformers/pull/27114

Can you check if applying this change fixes it?

**Comment by fxmarty** [comment] 2023-10-31 15:24
@ydshieh @gante Thank you! No this issue is unrelated unfortunately, as it also happens when the prompt `Elon Musk is a South` with `max_length=9` (only one padding token) and the extended attention mask

![image](https://github.com/huggingface/transformers/assets/9808326/a22b352a-8ca0-4834-ba42-e6f0df29853c)

that does not have any inf.

It may just be instability in the model, but it feels weird that it arises only when some attention mask rows are fully masked.

**Comment by gante** [comment] 2023-10-31 15:52
Well, I guess it needs another deep dive 😬

**Comment by ydshieh** [comment] 2023-11-02 15:46
I haven't been able to give a final conclusion, but in `LlamaMLP.forward`, change the `else` block to 

```python
            h1 = self.gate_proj(x)
            h2 = self.act_fn(h1)
            h3 = self.up_proj(x)
            h4 = self.down_proj(h2 * h3)
           down_proj = h4
```
and print their maximal absolute values, we will see their magnitude get unusually larger than before from layer 29 (0-based), and amplified to `255` in layer 30, than` h4` get `inf`.

**The question is what happened in `layer 29` for this input**: but I am afraid it's just some numerical issue and we don't really have the control. 

Will take a further look later when I get spare time.
```
------------------------------------
layer: 29
h1: 13.234375
h2: 4.5
h3: 18.15625
h4: 57.28125
------------------------------------
layer: 30
h1: 255.875
h2: 255.875
h3: 261.75
h4: inf
------------------------------------
layer: 31
h1: nan
h2: nan
h3: nan
h4: nan
------------------------------------
```


full
```
layer: 0
h1: 4.2109375
h2: 4.1484375
h3: 2.220703125
h4: 4.08203125
------------------------------------
layer: 1
h1: 19.75
h2: 19.75
h3: 18.328125
h4: 753.0
------------------------------------
layer: 2
h1: 2.8671875
h2: 2.025390625
h3: 2.2421875
h4: 4.1640625
------------------------------------
layer: 3
h1: 2.259765625
h2: 1.11328125
h3: 1.484375
h4: 0.423583984375
------------------------------------
layer: 4
h1: 4.4375
h2: 4.38671875
h3: 2.642578125
h4: 7.58203125
------------------------------------
layer: 5
h1: 3.142578125
h2: 2.416015625
h3: 2.431640625
h4: 1.2734375
------------------------------------
layer: 6
h1: 2.7265625
h2: 1.98828125
h3: 2.2578125
h4: 1.0556640625
------------------------------------
layer: 7
h1: 2.650390625
h2: 1.8046875
h3: 2.349609375
h4: 1.3251953125
------------------------------------
layer: 8
h1: 3.34375
h2: 1.76171875
h3: 2.6796875
h4: 1.8408203125
------------------------------------
layer: 9
h1: 4.37109375
h2: 2.328125
h3: 3.142578125
h4: 1.734375
------------------------------------
layer: 10
h1: 4.3046875
h2: 3.1796875
h3: 2.62109375
h4: 1.3212890625
------------------------------------
layer: 11
h1: 3.853515625
h2: 3.5078125
h3: 3.0078125
h4: 1.62890625
------------------------------------
layer: 12
h1: 3.33203125
h2: 2.224609375
h3: 2.548828125
h4: 1.005859375
------------------------------------
layer: 13
h1: 3.560546875
h2: 2.783203125
h3: 3.087890625
h4: 2.23828125
------------------------------------
layer: 14
h1: 3.841796875
h2: 2.9609375
h3: 2.63671875
h4: 0.67626953125
------------------------------------
layer: 15
h1: 3.609375
h2: 3.4765625
h3: 3.107421875
h4: 1.8994140625
------------------------------------
layer: 16
h1: 5.06640625
h2: 4.078125
h3: 4.28515625
h4: 5.421875
------------------------------------
layer: 17
h1: 5.35546875
h2: 5.33203125
h3: 3.740234375
h4: 2.919921875
------------------------------------
layer: 18
h1: 4.0
h2: 3.853515625
h3: 3.60546875
h4: 3.271484375
------------------------------------
layer: 19
h1: 4.46484375
h2: 4.4140625
h3: 3.75
h4: 4.16796875
------------------------------------
layer: 20
h1: 3.66796875
h2: 2.970703125
h3: 3.658203125
h4: 2.962890625
------------------------------------
layer: 21
h1: 5.34375
h2: 5.31640625
h3: 3.400390625
h4: 2.0234375
------------------------------------
layer: 22
h1: 3.318359375
h2: 3.203125
h3: 3.451171875
h4: 1.546875
------------------------------------
layer: 23
h1: 4.28125
h2: 4.22265625
h3: 4.109375
h4: 2.67578125
------------------------------------
layer: 24
h1: 4.21484375
h2: 3.220703125
h3: 3.15625
h4: 0.9482421875
------------------------------------
layer: 25
h1: 3.93359375
h2: 3.7109375
h3: 3.947265625
h4: 3.9921875
------------------------------------
layer: 26
h1: 4.3359375
h2: 3.865234375
h3: 4.37109375
h4: 1.7041015625
------------------------------------
layer: 27
h1: 4.55078125
h2: 3.400390625
h3: 3.630859375
h4: 1.4111328125
------------------------------------
layer: 28
h1: 4.90234375
h2: 4.4453125
h3: 7.54296875
h4: 2.0546875
------------------------------------
layer: 29
h1: 13.234375
h2: 4.5
h3: 18.15625
h4: 57.28125
------------------------------------
layer: 30
h1: 255.875
h2: 255.875
h3: 261.75
h4: inf
------------------------------------
layer: 31
h1: nan
h2: nan
h3: nan
h4: nan
------------------------------------
```

**Comment by ydshieh** [comment] 2023-11-06 12:47
After taking a further look, this doesn't seem to relate any bug but just the limitation of using fp16, and this is also depending on the input data.

One observation I found is: larger tensor values tend to appear when the prompt is (very) short.

Nothing more I can provide I am afraid.

**Comment by fxmarty** [comment] 2023-11-06 16:07
Thanks a lot @ydshieh. Did you notice any difference with whether rows are fully masked in the attention mask or not? 

We can probably close this one - at least it is good to know (at least) llama 7b has numerical instabilities during inference in fp16.

**Comment by ydshieh** [comment] 2023-11-06 16:16
> whether rows are fully masked in the attention mask or not?

Oh, I might made a mistake! You have `max_length=9` in the code snippet, so if I use long sequence, there is no padding!
OK, need to recheck !

**Comment by ArthurZucker** [comment] 2023-11-06 16:57
I think beam search with ROPE and fp16 has instabilities yes, reported here: #26332 if I am not mistaken this is what we have no? And I think a recent PR to fix this was merged: #26843 . 
But yeah I have a pretty huge list of bugs to process!

**Comment by ydshieh** [comment] 2023-11-06 18:03
FYI: here the issue is not even in the generation - the issue comes already in the first step: just encoding the input prompt.

**Comment by fxmarty** [comment] 2023-11-08 17:44
Same issue in layer 29/30 in https://github.com/PanQiWei/AutoGPTQ/issues/412. Unmasking fully masked padding rows solves the issue there as well.

![image](https://github.com/huggingface/transformers/assets/9808326/4de83f84-c1e7-4513-b8e8-cc5bb23baa9f)

**Comment by ydshieh** [comment] 2023-11-08 19:40
Great details! I am thinking if maybe the original training saw the unmasked row but now at inference time, it saw another version, which leads to this large value now. (similar to the different behavior of SDPA between torch 2.0.1 / 2.1.0 on GPU as we saw previously.)

**Comment by fxmarty** [comment] 2023-11-09 08:14
@ydshieh I want to give a try at some point to the original llama repo to see how padding is handled there.

**Comment by callanwu** [comment] 2023-12-11 13:33
mark

**Comment by ArthurZucker** [comment] 2024-01-30 10:13
I think computing ROPE in float32 percision should partly fix this

**Comment by ArthurZucker** [comment] 2024-03-25 08:37
I'll mark this as closed, because llama now computes rope in float32! 🥳 Feel free to ping me if you feel like this should not be closed

**Closed by ArthurZucker** 2024-03-25 08:37 UTC

**Comment by PIPItian** [comment] 2024-09-25 08:24
you can try to update optimum to the latest version to solve this
