### ISSUE TITLE
ImportError: cannot import name 'SeamlessM4TModel' from 'transformers' 

### ISSUE THREAD

**Issue by mwzkhalil** [huggingface/transformers#27061] opened 2023-10-25 08:24 UTC
### System Info

I encountered an ImportError when trying to import 'SeamlessM4TModel' from the 'transformers' library, 
Code:
`from transformers import AutoProcessor, SeamlessM4TModel

processor = AutoProcessor.from_pretrained("facebook/hf-seamless-m4t-large")
model = SeamlessM4TModel.from_pretrained("facebook/hf-seamless-m4t-large")`

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

nan

### Expected behavior

nan

**Comment by mwzkhalil** [comment] 2023-10-25 08:24
![image](https://github.com/huggingface/transformers/assets/77918472/fe3160d3-1f57-4123-8a62-4618a813d653)

**Comment by ArthurZucker** [comment] 2023-10-25 08:57
A duplicate of #27036, please make sure you install form source 🤗

**Closed by ArthurZucker** 2023-10-25 08:57 UTC
