### ISSUE TITLE
Broken link in Documentation 

### ISSUE THREAD

**Issue by datavistics** [huggingface/transformers#22077] opened 2023-03-10 08:57 UTC
### System Info

@sgugger 

Where I started
https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/text_generation#transformers.GenerationMixin.contrastive_search

What doesnt exist
https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/generation_strategies
https://huggingface.co/docs/transformers/main/en/main_classes/generation_strategies

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Go to the links above

### Expected behavior

The pages would exist.

**Comment by gante** [comment] 2023-03-10 09:48
Hey @datavistics -- the problem is not present on `main`, but rather in the previous release (which we can't fix unless we make a new release) 

See these docs: https://huggingface.co/docs/transformers/main/en/main_classes/text_generation

**Comment by datavistics** [comment] 2023-03-10 09:51
I still get the broken link here: https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationMixin.contrastive_search

**Comment by sgugger** [comment] 2023-03-10 12:46
Should be fixed by #22078 on main.

**Closed** 2023-03-10 13:28 UTC
