### ISSUE TITLE
Autotokenizer error "Already borrowed" when used on thread pool

### ISSUE THREAD

**Issue by Warra07** [huggingface/transformers#12658] opened 2021-07-12 15:14 UTC
## Environment info
- `transformers` version: 4.8.2
- Platform: Databricks
- Python version: 3.7.10
- PyTorch version (GPU?): GPU
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: Yes

## Information

Model I am using : camembert-base:

The problem arises when i try to use a tokenizer (from whatever model in my experiments) on multiple thread pools with an Autotokenizer, the error **RuntimeError: Already borrowed** get raised, i haven't tried if the same issues occure whith AutoModel, but i suspect it would, this makes it completly inefficient as it requires to duplicate the tokenizer on each thread (same for model), and is a real problem for packages like Petastorm  /  Horovod.

## To reproduce
Below you'll find a simple snippet of code to reproduce the error:
```Python
 from multiprocessing.dummy import Pool as ThreadPool
  
tokenizer =   AutoTokenizer.from_pretrained(pretrained_model_name_or_path="camembert-base")
def tokenizer_test(text):
    print(tokenizer(text))
    
pool = ThreadPool(10)  
data_list = ['this is a test'] * 10
pool.map(tokenizer_test, data_list)
pool.close()
pool.join()
```
However this works fine if i switch the Autotokenizer with CamembertTokenizer.from_pretrained("camembert-base") for example.

**Comment by LysandreJik** [comment] 2021-07-12 15:45
Duplicate of https://github.com/huggingface/tokenizers/issues/537

**Closed** 2021-08-21 15:02 UTC
