### ISSUE TITLE
Silero Models License Infringement

### ISSUE THREAD

**Issue by snakers4** [huggingface/transformers#17911] opened 2022-06-28 05:34 UTC
### Model description

Hi,

My name is Alexander, I am writing to you on behalf of Silero, a company maintaining our project [silero-models](https://github.com/snakers4/silero-models).
We noticed that our models are rehosted here - https://huggingface.co/spaces/pytorch/silero_tts or here https://huggingface.co/spaces?search=silero.
We did not explicitly grant Hugging Face, Inc. any sort of permission to rehost, relicense and profit from our work and models. 
Moreover it openly disregards our CC BY-NC-SA license.
Please immediately remove any of our models from your website and / or any of your resources.

Best,
Alexander

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available

**Comment by julien-c** [comment] 2022-06-28 06:50
closing as duplicate of https://github.com/huggingface/hub-docs/issues/216 let's address the issue there

**Closed by julien-c** 2022-06-28 06:50 UTC
Labels: New model
