### ISSUE TITLE
GPT-3

### ISSUE THREAD

**Issue by flozi00** [huggingface/transformers#4679] opened 2020-05-29 19:36 UTC
Paper: https://arxiv.org/pdf/2005.14165

GitHub: https://github.com/openai/gpt-3

Author: @8enmann

**Comment by thomwolf** [comment] 2020-05-29 19:38
Thanks, looks like a duplicate of #4658

**Closed by thomwolf** 2020-05-29 19:38 UTC
Labels: New model

**Comment by flozi00** [comment] 2020-05-29 19:40
Ups, haven't seen this on mobile.
My apologies
