### ISSUE TITLE
ImportError: cannot import name '_expand_mask' from 'transformers.models.bloom.modeling_bloom'

### ISSUE THREAD

**Issue by dipta007** [huggingface/transformers#29398] opened 2024-03-01 20:12 UTC
### System Info

```
- `transformers` version: 4.38.1
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.1 (cpu)
- Jax version: 0.4.23
- JaxLib version: 0.4.23
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

text models: @ArthurZucker and @younesbelkada 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://colab.research.google.com/drive/1tIgcJVofkzTic9ChhG8rNAQmFjrE1HYd?usp=sharing

### Expected behavior

It should run, but now its giving following error:

```
ImportError: cannot import name '_expand_mask' from 'transformers.models.bloom.modeling_bloom' (/usr/local/lib/python3.10/dist-packages/transformers/models/bloom/modeling_bloom.py)
```

**Comment by ArthurZucker** [comment] 2024-03-02 04:26
This is a duplicate of #28305, I am going to close this as we had a proper deprecation cycle for this. You should open the issue on the `open_flamingo` github repo 😉

**Closed by ArthurZucker** 2024-03-02 04:26 UTC
