### ISSUE TITLE
Unrecognized configuration class GPT2Config for AutoModelForSeq2SeqLM | Microsoft DialoGPT no longer working

### ISSUE THREAD

**Issue by RuolinZheng08** [huggingface/transformers#12726] opened 2021-07-15 03:01 UTC
## Information

Model I am using: Microsoft's DialoGPT

The problem arises when using:
* [x] the official example scripts: 

Since the morning of July 14th, the inference API has been outputting errors on [Microsoft's DialoGPT](https://huggingface.co/microsoft/DialoGPT-medium). It was working fine before July 14th.

Error

```
{'error': "Unrecognized configuration class <class 'transformers.models.gpt2.configuration_gpt2.GPT2Config'> 

for this kind of AutoModel: AutoModelForSeq2SeqLM.\nModel type should be one of 

BigBirdPegasusConfig, M2M100Config, LEDConfig, BlenderbotSmallConfig, MT5Config, T5Config, PegasusConfig, MarianConfig, MBartConfig, BlenderbotConfig, BartConfig, FSMTConfig, EncoderDecoderConfig, XLMProphetNetConfig, ProphetNetConfig."}
```

Query script as given on Hugging Face's site:

```python
import requests

API_URL = "https://api-inference.huggingface.co/models/microsoft/DialoGPT-medium"
headers = {"Authorization": "Bearer API_TOKEN"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()

output = query({
    "inputs": {
		"past_user_inputs": ["Which movie is the best ?"],
		"generated_responses": ["It's Die Hard for sure."],
		"text": "Can you explain why ?",
	},
})
```

@patrickvonplaten, @LysandreJik
I'm mentioning these two people as the guide says they are working on gpt2. Sorry if I pinged the wrong people!

**Comment by KenGrinder** [comment] 2021-07-15 04:11
Getting this error also. all fine-tuned models using Dialo giving this exact error.

**Comment by Narsil** [comment] 2021-07-15 09:08
Hi everyone.

Not really sure what happened here (the error is pretty confusing). It is fixed now anyway.

**Comment by Narsil** [comment] 2021-07-15 09:09
If someone pinned a model while it was having issues, please let me know, we might have to update them to fix them too !

**Closed** 2021-07-17 03:38 UTC

**Comment by Unn20** [comment] 2022-08-01 11:55
Hi @Narsil 

These 2 models need update:
- dbmdz/german-gpt2
- benjamin/gerpt2

**Comment by Narsil** [comment] 2022-08-01 13:32
dbmdz/german-gpt2 seems to be working  https://huggingface.co/dbmdz/german-gpt2?text=Heute+ist+sehr+sch%C3%B6nes+Wetter+in

It doesn't seem to be defined as `conversation`, is that what you're referring to ?
I am not sure how this model was defined and so if it actually works with conversation, but it doesn't seem to be the case.

The API works with text-generation for this model and it works fine.

`benjamin/gerpt2` seems to be exactly the same.

If you want to mark them as conversational you need to update the `pipeline_tag` https://huggingface.co/docs/hub/models-widgets#enabling-a-widget

Otherwise do you mind creating a new issue with the new error you're receiving to be able to reproduce (you can ping me)
