### ISSUE TITLE
Meet problems when I use the file src/transformers/models/llama/convert_llama_weights_to_hf.py to transfer LlaMa-7B

### ISSUE THREAD

**Issue by wwxxyy1996** [huggingface/transformers#30734] opened 2024-05-09 20:26 UTC
### System Info

![image](https://github.com/huggingface/transformers/assets/161870772/df755d6e-4ac8-4951-9e08-45e625f98952)
When I use the file convert_llama_weights_to_hf.py to converted LlaMa-7B weights to the Hugging Face Transformers format, an error raised for the line 154 and said "RuntimeError: shape '[32, 2, 2, 4096]' is invalid for input of size 16777216".

My command
python convert_llama_weights_to_hf.py     --input_dir ./ --model_size 7B --output_dir ./7B_hf

Here is my environments,
cuda-11.7, gcc-10.2.0, torch==2.0.0+cu117 torchvision==0.15.1+cu117, openai==0.27.8, transformers==4.41.0.dev0

Thank you very much!!

### Who can help?

@ArthurZucker @pcuenca @xe

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just use this code to convert the model. The model size (consolidated.00.pth file) is 13G.

python convert_llama_weights_to_hf.py     --input_dir ./ --model_size 7B --output_dir ./7B_hf

### Expected behavior

Could you give me some suggestions?

**Comment by ArthurZucker** [comment] 2024-05-10 06:09
Hey! This seems to be a duplicate of #30723, I'll check it out asap 😉

**Comment by wwxxyy1996** [comment] 2024-05-10 18:06
Thank you very much for your answering!! It is very important for me. Have a good weekend~

Best wishes,
Xinyi

**Comment by pep1t0** [comment] 2024-06-08 10:09
The problem is not solved by changing the transformer version

**Comment by Xe** [comment] 2024-06-10 04:52
Why am I marked as a person to help?

**Comment by ArthurZucker** [comment] 2024-06-18 13:18
No Idea @Xe ! 

And yes I know, I will look into the fix this week! Sorry all 🤗

**Closed** 2024-06-27 10:35 UTC
