### ISSUE TITLE
How can I load the finetuned BART model to memory?

### ISSUE THREAD

**Issue by tomaszgarbus** [huggingface/transformers#5055] opened 2020-06-16 11:47 UTC
I have finetuned a `facebook/bart-large` model following the example here: https://github.com/huggingface/transformers/blob/master/examples/summarization/finetune.py

As an output I got a `checkpointcheckpoint_ckpt_epoch_0.ckpt` file. How can I create a BartForConditionalGeneration instance with updated weights?

**Comment by sshleifer** [comment] 2020-06-16 11:59
Duplicate of #4144

**Closed by sshleifer** 2020-06-16 11:59 UTC

**Comment by tomaszgarbus** [comment] 2020-06-16 12:03
Thanks!
