### ISSUE TITLE
bug in bert pretraining 

### ISSUE THREAD

**Issue by dorost1234** [huggingface/transformers#10332] opened 2021-02-22 14:51 UTC
## Environment info

- `transformers` version: 4.3.2
- Platform: linux
- Python version: 3.7 
- PyTorch version (GPU?): 1.7 
- Tensorflow version (GPU?): - 
- Using GPU in script?: - 
- Using distributed or parallel set-up in script?: - 

### Who can help

- albert, bert, xlm: @LysandreJik

## Information

In this line https://github.com/huggingface/transformers/blob/e73a3e1891775a915846cc0f24b7e9a26d6688fb/src/transformers/data/data_collator.py#L381 you need to change 0.5 to 0.1 to match the description written that only in 10% you would like to change  tokens with randomly selected tokens. 

## To reproduce
Nothing to reproduce.

## Expected behavior

probs should match BERT paper.

**Comment by LysandreJik** [comment] 2021-02-22 15:49
Duplicate of https://github.com/huggingface/transformers/issues/10285

**Closed by LysandreJik** 2021-02-22 15:49 UTC
