### ISSUE TITLE
'Trainer' object has no attribute 'log_metrics'

### ISSUE THREAD

**Issue by Gpwner** [huggingface/transformers#10711] opened 2021-03-15 03:12 UTC
## Environment info

- `transformers` version:4.3.3
- Platform:Pytorch
- Python version:3.7.0
- PyTorch version (GPU?):GPU
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:NO

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_mlm.py
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.python run_mlm.py     --model_name_or_path release_model/     --dataset_name wikitext     --dataset_config_name wikitext-2-raw-v1     --do_train     --do_eval     --output_dir test-mlm --max_seq_length 128
2.Got an error:
```
[INFO|trainer.py:1408] 2021-03-15 11:10:32,884 >> Saving model checkpoint to test-mlm
[INFO|configuration_utils.py:304] 2021-03-15 11:10:32,886 >> Configuration saved in test-mlm/config.json
[INFO|modeling_utils.py:817] 2021-03-15 11:10:33,863 >> Model weights saved in test-mlm/pytorch_model.bin
Traceback (most recent call last):
  File "run_mlm.py", line 475, in <module>
    main()
  File "run_mlm.py", line 450, in main
    trainer.log_metrics("train", metrics)
AttributeError: 'Trainer' object has no attribute 'log_metrics'
```

## Expected behavior

The script finish without error.

**Comment by Gpwner** [comment] 2021-03-15 03:46
Btw ,these 3 API show similar error:
**API:**
```
 trainer.log_metrics("train", metrics)
 trainer.save_metrics("train", metrics)
trainer.save_state()
```

**error**
```
Traceback (most recent call last):
  File "run_mlm.py", line 476, in <module>
    main()
  File "run_mlm.py", line 452, in main
    trainer.save_state()
AttributeError: 'Trainer' object has no attribute 'save_state'
```

**Comment by NielsRogge** [comment] 2021-03-15 07:26
See #10446

**Comment by sgugger** [comment] 2021-03-15 12:08
Indeed. Please search the issues before opening one that is an exact duplicate of an existing one (see the link above for a resolution of your problem).

**Closed by sgugger** 2021-03-15 12:08 UTC
