### ISSUE TITLE
stopping criteria for TextGenerationPipeline

### ISSUE THREAD

**Issue by geronimi73** [huggingface/transformers#26280] opened 2023-09-20 06:06 UTC
### Feature request

pass stopping criteria or string to TextGenerationPipeline

### Motivation

it does not exist, have not found any way to do it at least, but would be _very_ useful

### Your contribution

none

**Comment by ArthurZucker** [comment] 2023-09-27 10:52
Hey! You can pass `generation_kwargs` to the pipeline, which are usually used for stopping criteria such as `max_length, max_new_tokens, max_time` . You can also pass some `stopping_criteria` argument to the generate function using `generation_kwargs = {stopping_criteria = StoppingCriteriaList: [MaxTimeCriteria(32)] }.

```python
from transformers import pipeline, StoppingCriteriaList, MaxTimeCriteria

# Initialize the text generation pipeline
generator = pipeline("text-generation")

# Define the stopping criteria using MaxTimeCriteria
stopping_criteria = StoppingCriteriaList([MaxTimeCriteria(32)])

# Define the generation_kwargs with stopping criteria
generation_kwargs = {
    "max_length": 100,  # Maximum length of the generated text
    "max_new_tokens": 10,  # Maximum number of new tokens to generate
    "generation_kwargs": {"stopping_criteria": stopping_criteria}  # Add stopping criteria to generation_kwargs
}

# Pass the generation_kwargs to the pipeline
generated_text = generator(
    "Hey!  How are you able.",
    **generation_kwargs
)

# Print the generated text
print(generated_text[0]["generated_text"])
>>> Hey!  How are you able.  Do you have a job or do you have
```

**Comment by ArthurZucker** [comment] 2023-09-27 10:54
This should probably be added to the documentation!

**Comment by LysandreJik** [comment] 2023-09-28 08:13
cc @MKhalusova who is currently working on the `generate` docs!

**Comment by Tanman2001** [comment] 2023-10-06 03:21
Is this a duplicate of #17562?

If so, it seems the only reason that older issue is still open is because of the missing documentation. If the documentation is fixed then both can be closed.

**Closed** 2023-10-06 04:10 UTC

**Comment by peng-yiwen** [comment] 2024-06-21 13:04
According to my experiments, setting
```python
generation_kwargs = {
    "max_new_tokens": 1000,  # Maximum number of new tokens to generate
    "generation_kwargs": {"stopping_criteria": stopping_criteria}  # Add stopping criteria to generation_kwargs
}
``` 
is not feasible for passing a stopping criteria into a pipeline. Instead, if we let "stopping_criteria" out of "generation_kwargs", it then works well. As below:

```python
generation_kwargs = {
    "max_new_tokens": 1000,  # Maximum number of new tokens to generate
    "stopping_criteria": stopping_criteria,
}
```
