### ISSUE TITLE
Inconsistency between CLIPTokenizer and CLIPTokenizerFast

### ISSUE THREAD

**Issue by sayanshaw24** [huggingface/transformers#26887] opened 2023-10-18 00:23 UTC
### System Info

- `transformers` version: 4.30.2
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.11
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 1.12.1+cpu (False)
- Tensorflow version (GPU?): 2.9.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Import CLIPTokenizer and CLIPTokenizerFast
2. Create the "openai/clip-vit-base-patch32" pretrained tokenizers
3. Compare input ids of tokenizers with some example text using words with apostrophes (e.g., you're, don't, her's, etc.)
```
from transformers import CLIPTokenizer, CLIPTokenizerFast

slow_tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-base-patch32")
fast_tokenizer = CLIPTokenizerFast.from_pretrained("openai/clip-vit-base-patch32")

test_str = "you're, don't, her's"
clip_slow_out = slow_tokenizer(test_str)
clip_fast_out = fast_tokenizer(test_str)

slow_input_ids = clip_slow_out ['input_ids']
fast_input_ids = clip_fast_out ['input_ids']

np.testing.assert_array_equal(slow_input_ids, fast_input_ids)
```

### Expected behavior

The input ids should be the same for both regular and fast tokenizers, however CLIPTokenizer tokenizes apostrophes separately (['you', ''', 're']) but CLIPTokenizerFast tokenizes together (['you', ''re']).

Which of these results are the correct expected values? They should be consistent, should they not?

**Comment by ArthurZucker** [comment] 2023-10-18 09:48
Hey! This is a duplicate of #22166 I believe!

**Closed** 2023-10-19 17:49 UTC
