### ISSUE TITLE
Why run_translation.py automatically runs on CPU?

### ISSUE THREAD

**Issue by Why1005** [huggingface/transformers#11671] opened 2021-05-11 05:44 UTC
I use examples/pytorch/translation/run_translation.py fine-tune mbart-large-cc25 on my datasets, it automatically runs on CPU.  I have 2 GPU, but only one is Nvidia.It is RTX 2080super. 

python main.py \
--model_name_or_path facebook/mbart-large-cc25 \
--do_train  \
--do_eval \
--source_lang en_XX \
--target_lang zh_CN \
--train_file /data/2WangHongyu/bioNMT_WHY/train.json \
 --validation_file /data/2WangHongyu/bioNMT_WHY/dev.json \
 --output_dir /output \
--per_device_train_batch_size=4 \
--per_device_eval_batch_size=4 \
--overwrite_output_dir \
--predict_with_generate \
 --cache_dir /model/2WangHongyu/mbart-large

**Comment by LysandreJik** [comment] 2021-05-11 08:05
Duplicate of https://github.com/huggingface/transformers/issues/11548#issuecomment-831159016

Could you please answer to 

> Hi! Is your CUDA environment correctly set up? What is the output of the following in your environment?
> 
> `python -c "import torch;print(torch.cuda.is_available())"`

and how do you identify that it's not running on GPU? Could you put the accompanying logs? At which point do you see it running on CPU when you think it should be running on GPU?

**Comment by Why1005** [comment] 2021-05-11 08:30
> Duplicate of [#11548 (comment)](https://github.com/huggingface/transformers/issues/11548#issuecomment-831159016)
> 
> Could you please answer to
> 
> > Hi! Is your CUDA environment correctly set up? What is the output of the following in your environment?
> > `python -c "import torch;print(torch.cuda.is_available())"`
> 
> and how do you identify that it's not running on GPU? Could you put the accompanying logs? At which point do you see it running on CPU when you think it should be running on GPU?

True…
While the program is running, the GPU utilization is close to 0%, and the CPU utilization is close to 10%.

**Closed** 2021-05-14 06:13 UTC
