### ISSUE TITLE
When I updated my transformers to the latest, the previously trained model loaded with an error

### ISSUE THREAD

**Issue by wulaoshi** [huggingface/transformers#7262] opened 2020-09-20 05:19 UTC
## Environment info

     
- `transformers` version:'3.1.0'
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by wulaoshi** [comment] 2020-09-20 05:21
![image](https://user-images.githubusercontent.com/27938964/93694930-3f812e80-fb44-11ea-938e-6e36e51bf183.png)

**Comment by patrickvonplaten** [comment] 2020-09-20 16:51
Duplicate of https://github.com/huggingface/transformers/issues/6882 I think

**Comment by wulaoshi** [comment] 2020-09-21 02:03
> Duplicate of #6882 I think

Thanks. I'll look into it

**Comment by wulaoshi** [comment] 2020-09-21 02:13
> Duplicate of #6882 I think

Thanks. I'll look into it.

**Closed** 2020-11-29 11:50 UTC
Labels: wontfix
