### ISSUE TITLE
'tiiuae/falcon-7b' is not supported using flash attention 2

### ISSUE THREAD

**Issue by nirdoshrawal009** [huggingface/transformers#26442] opened 2023-09-27 13:16 UTC
ValueError: The current architecture does not support Flash Attention 2.0. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new

**Comment by LysandreJik** [comment] 2023-09-28 06:43
cc @younesbelkada  :)

**Comment by LysandreJik** [comment] 2023-09-28 06:45
I believe this is actually a duplicate of https://github.com/huggingface/transformers/issues/26443, closing in favor of this one

**Closed by LysandreJik** 2023-09-28 06:45 UTC

**Comment by younesbelkada** [comment] 2023-09-28 09:21
Hi @nirdoshrawal009 
Please take a look at my comment here: https://github.com/huggingface/transformers/issues/26443#issuecomment-1738789689
For more details
