### ISSUE TITLE
Problem with https://transformer.huggingface.co/doc/gpt2-xl

### ISSUE THREAD

**Issue by MarxEngelsLeninStalin** [huggingface/transformers#3701] opened 2020-04-08 15:55 UTC
Hi, when using it, simple switch the button up to xl one. When you try to generate a prediction of words; it will simply never load regardless of what all the other setting are on. Every other gpt2 model size works; expect the xl one. Tried it on Android and Linux same problem and different browsers Firefox and Google Chrome same problem nothing to with addons cause the same problem occurs with them all off.

**Comment by LysandreJik** [comment] 2020-04-08 17:14
Duplicate of https://github.com/huggingface/transformers/issues/3452.

We should just remove the option cc @julien-c

**Comment by julien-c** [comment] 2020-04-08 17:38
You’re right, I’ll get on it

**Comment by julien-c** [comment] 2020-04-08 17:39
Also best username ever, @MarxEngelsLeninStalin

**Comment by Marxist-Leninist** [comment] 2020-04-09 17:01
Oh, I like that model as someone who has problems with spelling/grammar and fatigue it's useful to use xl one has more knowledge on it (yes I know it's not accurate but more accurate then large model). Is there any prospect of it being turned on again in the future?

**Comment by LysandreJik** [comment] 2020-06-10 00:03
@Marxist-Leninist, unfortunately adding it back isn't on our near future roadmap.

**Closed** 2020-06-10 00:02 UTC
Labels: wontfix
