### ISSUE TITLE
Encoding parameter

### ISSUE THREAD

**Issue by PrasathMuru** [huggingface/transformers#20922] opened 2022-12-28 12:21 UTC
### Feature request

##transformers.AutoModel.from_pretrained()##  module allows to load pretrained models from local directories as well. The local pickle files path is an argument of the above function. These files can have different encoding types. 

A parameter called 'encoding' can be added in the parameter list similar to 

pandas.read_csv('path/to/csv/file',encoding='utf-8') 

which takes encoding type as parameter. But this proposed encoding feature must be enabled only while loading local files and should not take parameters while loading models from other sources (like HF-Hub etc).

### Motivation

I face Unicode-Decode error while loading pickled model files from local directory. To overcome this issue, the above feature would help to avoid the unicode-decode error.

### Your contribution

Unfortunately, I can't contribute now.

**Comment by sgugger** [comment] 2022-12-29 07:24
Duplicate of #20923

**Closed by sgugger** 2022-12-29 07:24 UTC
