### ISSUE TITLE
Return output probabilities with Generate function 

### ISSUE THREAD

**Issue by tshrjn** [huggingface/transformers#8656] opened 2020-11-19 12:44 UTC
# 🚀 Feature request

Output the token probabilities along with the tokens when generating sequence.

## Motivation

For understanding model confidence, this is quite useful. 
Also, for abstractive QA with long contexts, one needs to use doc-strides to take into account the contexts & then choose the best answer according to the probability of the generated text.

## Your contribution

I can try submitting a PR for non-beam decoding, but guidance would be appreciated.
Also, are there any existing solutions to this issue? If so, what & where?

**Comment by patrickvonplaten** [comment] 2020-11-23 18:07
Duplicate of https://github.com/huggingface/transformers/issues/7654 . But yes, it seems like many people are asking for this feature and it should be quite straight-forward to implement it... -> feel free to give a shot :-)

**Comment by miguelvictor** [comment] 2021-01-07 11:05
Hi. When can we expect this to be released? 😊

**Comment by patrickvonplaten** [comment] 2021-01-07 11:33
Next week Tuesday or Wednesday :-)

**Comment by moqingyan** [comment] 2021-04-13 15:17
Hey! Can anyone point me to the API/code location of this feature? Sorry if I have missed something. :) Thank you!

**Comment by miguelvictor** [comment] 2021-04-14 00:38
@moqingyan https://huggingface.co/transformers/internal/generation_utils.html

**Comment by moqingyan** [comment] 2021-04-14 05:03
> @moqingyan https://huggingface.co/transformers/internal/generation_utils.html

Thank you!

My problem was: I set the configuration `output_scores` to `True` in the `generate` function and failed obtain the scores in the returned results. After I struggled in the libraries for hours, I finally figured out I also need to set `return_dict_in_generate` to `True` to obtain the attention values from the `generate` function. :) 

I think this behavior is non-intuitive, as I have specified I need the scores in the output already. But anyway I figured this out. Hope this comment is helpful to anyone who runs into this issue.

**Closed** 2021-05-16 15:02 UTC
