### ISSUE TITLE
Llama 2: NaN values when torch_dtype=torch.float16 and padding_side="left"

### ISSUE THREAD

**Issue by ValeKnappich** [huggingface/transformers#25311] opened 2023-08-04 08:10 UTC
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.21.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker @younesbelkada 

Llama 2 seems to produce NaN-values when `torch_dtype=torch.float16` and `padding_side="left"`. The behavior seems very odd to me. See the MWE below.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig

WITH_DTYPE_KWARG = True
LEFT_PADDING = True

model_id = "meta-llama/Llama-2-7b-hf"

if WITH_DTYPE_KWARG:
    model = AutoModelForCausalLM.from_pretrained(model_id, low_cpu_mem_usage=True, torch_dtype=torch.float16).cuda()
else:
    model = AutoModelForCausalLM.from_pretrained(model_id, low_cpu_mem_usage=True).cuda()

if LEFT_PADDING:
    tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side="left")
else:
    tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side="right")

tokenizer.pad_token = tokenizer.eos_token

inputs = [
    "Short input",
    "Long long long input with lots of tokens so that there is a padding",
    "Short input",
    "Long long long input with lots of tokens",
]

enc = tokenizer(inputs, padding=True, return_tensors="pt").to(model.device)
o = model(**enc)
assert o.logits.isnan().sum().item() == 0
```

The assertion fails only when both WITH_DTYPE_KWARG  and LEFT_PADDING  are true. However, there also seems to be some interaction with the input, the problem does not appear for every input.

### Expected behavior

All variants should work or a meaningful error message should be shown.

**Comment by ArthurZucker** [comment] 2023-08-04 08:51
Closing as duplicate of #25065, but thanks a lot for putting effort in having a nice small reproducer!

**Closed by ArthurZucker** 2023-08-04 08:51 UTC
