### ISSUE TITLE
Request to add MobileBert

### ISSUE THREAD

**Issue by msahamed** [huggingface/transformers#4408] opened 2020-05-17 06:33 UTC
# 🌟 New model addition
MobileBERT
## Model description

MobileBERT is a thin version of BERT_LARGE, while equipped with bottleneck structures and a carefully designed balance between self-attentions and feed-forward networks.

## Open source status

* [ ] the model implementation is available: (give details)
https://github.com/google-research/google-research/tree/master/mobilebert

* [ ] the model weights are available: (give details)
https://storage.googleapis.com/cloud-tpu-checkpoints/mobilebert/uncased_L-24_H-128_B-512_A-4_F-4_OPT.tar.gz

* [ ] who are the authors: (mention them, if possible by @gh-username)
Google LLC
Xiaodan Song
Zhiqing Sun
Hongkun Yu
Denny Zou

**Comment by julien-c** [comment] 2020-05-18 13:49
Duplicate of #4185

**Closed by julien-c** 2020-05-18 13:49 UTC
Labels: New model
