### ISSUE TITLE
Batched pipeline

### ISSUE THREAD

**Issue by berryweinst** [huggingface/transformers#6327] opened 2020-08-07 15:10 UTC
Hi, 

Is there a way to run batches with QuestionAnsweringPipeline rather than just one example?

Thanks.

**Comment by Alex-Fabbri** [comment] 2020-08-08 17:16
Yes, building off of the model and example [here](https://huggingface.co/twmkn9/albert-base-v2-squad2): 

```
from transformers.pipelines import pipeline

model_name = "twmkn9/albert-base-v2-squad2"

nlp = pipeline('question-answering', model=model_name, tokenizer=model_name)
QA_input = {
    'question': 'Why is model conversion important?',
    'context': 'The option to convert models between FARM and transformers gives freedom to the user and let people easily switch between frameworks.'}, {
    'question': 'What is the name of the repository ?',
    'context': 'Pipeline have been included in the huggingface/transformers repository. '
    }
res = nlp(QA_input, handle_impossible_answer=True)
print(res)
# [{'score': 0.2479676753282547, 'start': 59, 'end': 132, 'answer': 'gives freedom to the user and let people easily switch between frameworks.'}, {'score': 0.5168691277503967, 'start': 35, 'end': 71, 'answer': 'huggingface/transformers repository.'}]


```

**Comment by nikoletta-toth** [comment] 2020-09-21 10:48
Hi. 
How can one specify the batch number for the inference? Or what is the default value?

Thanks!

**Comment by vinicius-cleves** [comment] 2020-11-27 05:00
Possible duplicate of #3007

**Closed** 2021-03-06 00:17 UTC
Labels: wontfix

**Comment by patrick-vtc** [comment] 2022-02-10 19:02
still an open point. highly required, any information on the progress?

**Comment by LysandreJik** [comment] 2022-02-22 18:44
This is implemented in recent versions: https://huggingface.co/docs/transformers/master/en/main_classes/pipelines#pipeline-batching

cc @Narsil

**Comment by Narsil** [comment] 2022-02-23 08:40
For the sake of completion: 
```python
pipe = pipeline('question-answering', model=model_name, tokenizer=model_name)
questions = [{"question": "Who am I ?", "context": "There is something about me"}, .... ]
for answer in pipe(questions, batch_size=16):
    print(answer)
````

**Comment by thangld201** [comment] 2025-03-21 03:30
Hi @Narsil @LysandreJik , the example codes no longer work 
```
  File "/home/ubuntu/miniconda3/envs/my_env/lib/python3.10/site-packages/transformers/pipelines/question_answering.py", line 432, in preprocess
    text=example.question_text if question_first else example.context_text,
AttributeError: 'list' object has no attribute 'question_text'
```

Any pointer ?
