### ISSUE TITLE
output probabilities of generated sequences in generate function

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/transformers#7654] opened 2020-10-08 05:57 UTC
# 🚀 Feature request

output probabilities of generated sequences in generate function (generation utils)

thank you so much! :)

**Comment by patrickvonplaten** [comment] 2020-10-08 13:12
Duplicate of https://github.com/huggingface/transformers/issues/3891

**Comment by patrickvonplaten** [comment] 2020-11-23 18:07
Actually, those issues are different and we should probably provide this functionality!

**Closed** 2021-04-26 15:02 UTC
Labels: wontfix
