### ISSUE TITLE
mt5 getting nans with fp16

### ISSUE THREAD

**Issue by dorost1234** [huggingface/transformers#10819] opened 2021-03-20 06:44 UTC
## Environment info

- `transformers` version: 4.4.2
- Platform: linux
- Python version: 3.7
- PyTorch version (GPU?): 1.8 
- Tensorflow version (GPU?): - 
- Using GPU in script?: - 
- Using distributed or parallel set-up in script?: - 

### Who can help

 t5: @patrickvonplaten, @patil-suraj

## Information

I am using mt5-small model:
* the problem arises when using fp16 with mt5

The tasks I am working on is:
* translation

## To reproduce

`python run_translation.py     --model_name_or_path google/mt5-small     --do_train     --do_eval     --source_lang en     --target_lang ro     --dataset_name wmt16     --dataset_config_name ro-en     --output_dir  test/tst-translation     --per_device_train_batch_size=4     --per_device_eval_batch_size=4     --overwrite_output_dir     --predict_with_generate --max_train_samples 100 --fp16`

outputs:
```
***** eval metrics *****
  epoch                     =     3.0
  eval_bleu                 =  0.0039
  eval_gen_len              =    2.95
  eval_loss                 =     nan
  eval_mem_cpu_alloc_delta  =     4MB
  eval_mem_cpu_peaked_delta =     5MB
  eval_mem_gpu_alloc_delta  =     0MB
  eval_mem_gpu_peaked_delta =  1080MB
  eval_runtime              = 72.1865
  eval_samples              =    1999
  eval_samples_per_second   =  27.692
```

## Expected behavior

being able to use fp16 with mt5 models. Thank you very much for your help, this is really crucial for me to be able to run these models with fp16 to be able to fit more data into old GPUs I have access to and I appreciate a lot your help.

**Comment by patrickvonplaten** [comment] 2021-03-22 08:30
Duplicate of https://github.com/huggingface/transformers/issues/10830

**Comment by dorost1234** [comment] 2021-03-22 09:10
Hi @patrickvonplaten  this is not exact duplicate, I am using mt5-small and the other user in  #10830 is using t5-large, I appreciate considering both thank you

**Comment by stas00** [comment] 2021-03-29 22:46
@dorost1234, please kindly test if this PR fixes the problem: https://github.com/huggingface/transformers/pull/10956

**Comment by dorost1234** [comment] 2021-03-31 08:45
@stas00  thank you very much for the contributions, it now works for me for the mt5-small, I am running some more experiments with it and update.

**Comment by dorost1234** [comment] 2021-03-31 21:29
Dear @stas00 
I tested more codes, without deepspeed, it works fine with setting the feedforward layer to float32, as suggested in the PR, but the moment I switch to deepspeed I still get nan issue in my codes. I greatly appreciate if you can spare some moments from your precious time and provide me with a suggestion for the case of deepspeed for the same problem. Thank you very much

**Comment by stas00** [comment] 2021-03-31 21:54
I was just thinking about it, so thank you for confirming that. 

Deepspeed is not using `autocast` so in essence the proposed fixed makes no difference under Deepspeed as we aren't running under `autocast` in the first place. Let's ask the DeepSpeed developers https://github.com/microsoft/DeepSpeed/issues/908

**Comment by dorost1234** [comment] 2021-03-31 21:59
Dear @stas00 
Sure, thank you very much for coming back to me, I will add this to the other thread, sure, I will open up an issue on deepspeed, do you mind telling me how to formulate this problem to make it easier for them to understand, please accept my apologies, my knowledge is limited on deepspeed and not sure the best way to put it for them, thanks a lot

**Comment by stas00** [comment] 2021-03-31 22:06
I already did - please see the link in my last comment

**Comment by dorost1234** [comment] 2021-03-31 22:07
oh, great, thank you very much

**Comment by dorost1234** [comment] 2021-04-02 14:11
Dear @stas00 
I tested the code more (without deepspeed) on larger scale and when I train on opus100 (I train on 20 languages of it), after 2000 iterations with mt5-small, after applying the fix, this gets nan still. I will share with you a reproducible code soon. thanks a lot for all the great work.

**Closed** 2021-06-07 15:18 UTC
