### ISSUE TITLE
Error when running the script 'run_summarization_finetuning.py'

### ISSUE THREAD

**Issue by allenguo92** [huggingface/transformers#1982] opened 2019-11-28 18:33 UTC
## 🐛 Bug

Model I am using Bert:

Language I am using the model on English:

The problem arise when using:
* [x] the official example scripts: run_summarization_finetuning.py

The tasks I am working on is:
* [x] other task or dataset: summarization, cnn-dailymail dataset(stories) 

## To Reproduce

1.Download cnn-dailymail dataset from [official website](https://cs.nyu.edu/~kcho/DMQA/)(only 'stories' for 'cnn' & 'dailymail').
2.Use the path which refers to the location of dataset to specify parameter '--data_dir' and specify '--output_dir' with my own dir.
3.Run the script 'run_summarization_finetuning.py' with command 'CUDA_VISIBLE_DEVICES=0 python run_summarization_finetuning.py --data_dir xxx --output_dir xxxx' via pycharm. (anonymous path 'xxx' & 'xxxx')

Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/transformers/examples/run_summarization_finetuning.py", line 487, in <module>
    main()
  File "/root/transformers/examples/run_summarization_finetuning.py", line 452, in main
    global_step, tr_loss = train(args, model, tokenizer)
  File "/root/transformers/examples/run_summarization_finetuning.py", line 219, in train
    for step, batch in enumerate(epoch_iterator):
  File "/root/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1002, in __iter__
    for obj in iterable:
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/root/transformers/examples/run_summarization_finetuning.py", line 74, in collate
    encode_for_summarization(story, summary, tokenizer) for story, summary in data
  File "/root/transformers/examples/run_summarization_finetuning.py", line 74, in <listcomp>
    encode_for_summarization(story, summary, tokenizer) for story, summary in data
  File "/root/transformers/examples/utils_summarization.py", line 143, in encode_for_summarization
    for line in story_lines
  File "/root/transformers/examples/utils_summarization.py", line 143, in <listcomp>
    for line in story_lines
AttributeError: 'BertTokenizer' object has no attribute 'add_special_tokens_single_sequence'

## Expected behavior

Complete the missing function 'add_special_tokens_single_sequence' in BertTokenizer and other related 'Tokenizer', such as xlnet, roberta...

## Environment

* OS: Ubuntu 5.4.0-6ubuntu1~16.04.9
* Python version: python3.7(anaconda)
* PyTorch version:1.1.0
* PyTorch Transformers version (or branch):transformers-2.2.0
* Using GPU ?Yes
* Distributed of parallel setup ?No

**Comment by thomwolf** [comment] 2019-12-05 11:20
cc @rlouf

**Comment by rlouf** [comment] 2019-12-05 21:47
@allenguo92 thank you for reporting this! The problem is addressed in a PR that should be merged soon! #1773

**Comment by vdperera** [comment] 2019-12-06 17:45
I was looking at the same script as an example on how to use/train the new PreTrainedEncoderDecoder class. @rlouf in the PR you mentioned it looks like the fine tuning code is now gone, any chance is going to be added back? Thanks :)

**Closed** 2020-02-11 18:47 UTC
Labels: wontfix
