### ISSUE TITLE
RAG: NameError: name 'load_dataset' is not defined

### ISSUE THREAD

**Issue by shamanez** [huggingface/transformers#7551] opened 2020-10-03 09:12 UTC
I tried to load RAG according to the documentation. 

` retriever = RagRetriever.from_pretrained("facebook/rag-token-base", index_name="exact", use_dummy_dataset=True)
`

The above line gave the following error.

**/python3.6/site-packages/transformers/retrieval_rag.py", line 220, in __init__
    self.dataset = load_dataset(
NameError: name 'load_dataset' is not defined**

**Comment by sgugger** [comment] 2020-10-03 20:56
I think this is a duplicate of #7536. RAG requires datasets and faiss to be installed in your environment to work properly.
The fix with proper error messages is on in #7537.

**Closed** 2020-10-07 08:53 UTC
