### ISSUE TITLE
 NameError: name 'PartialState' is not defined.

### ISSUE THREAD

**Issue by gli-mrunal** [huggingface/transformers#22846] opened 2023-04-19 01:23 UTC
I am using the following version of transformer, datasets and huggingface_hub. 

![image](https://user-images.githubusercontent.com/77198742/232941383-cc398bb4-88c0-4a12-9ff1-c59f8c5aa1a6.png)

I am running into the following error:

```sh
 NameError: name 'PartialState' is not defined.
```

How to resolve this issue  to work with my versions of the  transformer, datasets and huggingface_hub ?
My code was running just fine until yesterday.

**Comment by amyeroberts** [comment] 2023-04-19 11:35
Closing, as this issue is a duplicate of a comment on #22816, where it it being followed up on.

**Closed by amyeroberts** 2023-04-19 11:35 UTC
