### ISSUE TITLE
bert-base-uncased have weird result on Squad 2.0 

### ISSUE THREAD

**Issue by f422661** [huggingface/transformers#2672] opened 2020-01-29 15:18 UTC
I followed the example to fine-tuning BERT on SQuAD2.0:
https://huggingface.co/transformers/examples.html#fine-tuning-bert-on-squad1-0

I run the code as follow:
```
python /content/drive/My\ Drive/squad2/run_squad.py \
  --model_type bert \
  --model_name_or_path bert-base-uncased \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file /content/drive/My\ Drive/squad2/train-v2.0.json \
  --predict_file /content/drive/My\ Drive/squad2/dev-v2.0.json \
  --per_gpu_train_batch_size 12 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --output_dir /content/drive/My\ Drive/squad2_model/
```
However, I got weird results as follow:

```
Results: {'exact': 40.722648024930514, 'f1': 44.3783712849203, 'total': 11873, 'HasAns_exact': 81.5620782726046, 'HasAns_f1': 88.88400847939587, 'HasAns_total': 5928, 'NoAns_exact': 0.0, 'NoAns_f1': 0.0, 'NoAns_total': 5945, 'best_exact': 50.11370336056599, 'best_exact_thresh': 0.0, 'best_f1': 50.11370336056599, 'best_f1_thresh': 0.0}
```
'NoAns_exact' and 'NoAns_f1' are zero.

Do I miss anything when running the example code?

**Comment by cronoik** [comment] 2020-01-29 15:47
Probably a duplicate of #2651

**Comment by LysandreJik** [comment] 2020-01-29 18:48
Hi, running the exact same command but specifying you're using the version 2 with `--version_2_with_negative` gives me the following results:

```
01/29/2020 13:20:35 - INFO - __main__ -   Results: {'exact': 73.29234397372188, 'f1': 76.50792180947842, 'total': 11873, 'HasAns_exact': 71.94669365721997, 'HasAns_f1': 78.38707079013807, 'HasAns_total': 5928, 'NoAns_exact': 74.63414634146342, 'NoAns_f1': 74.63414634146342, 'NoAns_total': 5945, 'best_exact': 73.29234397372188, 'best_exact_thresh': 0.0, 'best_f1': 76.50792180947839, 'best_f1_thresh': 0.0}
```

Here are the exact arguments I used:
```
--model_type=bert --model_name_or_path=bert-base-uncased --do_train --do_eval --do_lower_case --version_2_with_negative --train_file=../../datasets/squad-v2.0/train-v2.0.json --predict_file=../../datasets/squad-v2.0/dev-v2.0.json --per_gpu_train_batch_size=12 --learning_rate=3e-5 --num_train_epochs=2.0 --max_seq_length=384 --doc_stride=128 --save_steps=10000 --output_dir=output_pt --overwrite_output_dir
```

**Comment by f422661** [comment] 2020-01-30 00:14
@LysandreJik thanks for your reply.
I will try again.

**Closed** 2020-01-31 09:36 UTC

**Comment by ppyu** [comment] 2020-10-16 02:27
My result is the same as yours. Maybe we not use the argument `--version_2_with_negative` ?
