### ISSUE TITLE
Recent changes is causing "found at least two devices"

### ISSUE THREAD

**Issue by casper-hansen** [huggingface/transformers#32420] opened 2024-08-05 05:18 UTC
### System Info

transformers 4.43.3, python 3.10, linux

### Who can help?

@ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I have received multiple reports that model loading behaviour recently changed which is causing a device error. This can usually be fixed by specifying the `device_map`, but prior to recent changes (I don't know when this happened), the model was loaded and could inference without any issues on multiple GPUs.

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0
```

Referenced issues:
https://github.com/casper-hansen/AutoAWQ/issues/510
https://github.com/casper-hansen/AutoAWQ/issues/558
https://github.com/casper-hansen/AutoAWQ/issues/571

### Expected behavior

The expected behavior is that we do not see these errors with the default settings of `device_map=None`. I am generally not sure what exactly changed, so it is hard to be more precise

**Comment by ArthurZucker** [comment] 2024-08-26 15:16
Thanks for reporting, could you try with the latest release? 
Otherwise, sorry for the inconvenience and cc @SunMarc !

**Comment by davedgd** [comment] 2024-08-28 02:40
> Thanks for reporting, could you try with the latest release? Otherwise, sorry for the inconvenience and cc @SunMarc !

I tested this today, and it's still an issue with the latest transformers release (v4.44.2) at time of writing.

**Comment by ArthurZucker** [comment] 2024-08-28 09:34
😢 I don't know if this is accelerate or not so pinging @muellerzr as well

**Comment by muellerzr** [comment] 2024-08-28 10:57
Looks like AWQ is another model that can't be fast-loaded. Will put in a fix

**Comment by casper-hansen** [comment] 2024-08-29 10:26
@muellerzr For reference, this error occurs when we want to run inference to quantize the model. I have not received similar reports for inference of quantized models. So in other words, this is happening when running models with BF16/FP16.

**Comment by trevor-m** [comment] 2024-10-07 23:59
I am also encountering this issue and here is what's happening in my case:

1. During `LlamaAttention.__init__()`, the `LlamaRotaryEmbedding` module is initialized. No `device` arg is provided: https://github.com/huggingface/transformers/blob/d6ba1ac041ac0b07bc589dd82a67cfb76f75d0f9/src/transformers/models/llama/modeling_llama.py#L304
2.  In `LlamaRotaryEmbedding.__init__()`, the `inv_freq` and `original_inv_freq` tensors are created and since `device` is not provided they are placed on the cpu
3. During execution, in `_dynamic_frequency_update()` if `inv_freq` is [growing, then the tensor will be recomputed and placed correctly on the specified device (cuda for me)](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L135). However, if it [needs to reset, the `original_inv_freq` is used](https://github.com/huggingface/transformers/blob/d6ba1ac041ac0b07bc589dd82a67cfb76f75d0f9/src/transformers/models/llama/modeling_llama.py#L142) which as I mentioned was placed on the cpu. This would cause the two device error in the forward() call. 

For dynamic frequency updates, this can be fixed with a simple change like this: https://github.com/trevor-m/transformers/commit/1a7e62ab585a2b6ff0feab3256a0946449ee6954

**Comment by SunMarc** [comment] 2024-10-08 14:27
Thanks for the nice report ! It seems that there is indeed a device mismatch here. Would you like to open a PR to fix this ? Could you also share a snippet to reproduce the error you are getting ? Thanks a lot. cc @gante

**Comment by trevor-m** [comment] 2024-10-10 19:50
Let me try to make a small reproducer. I wonder if using `register_buffer` for the `original_inv_freq` would allow it to move alongside the whole model when we change devices.

**Comment by davedgd** [comment] 2024-10-13 20:16
Just following up here since it may be relevant to @trevor-m's issues. It turns out my attempts to fix the AutoAWQ code directly based on @SunMarc's suggestions don't fully resolve the issue unfortunately (i.e., see https://github.com/casper-hansen/AutoAWQ/pull/630#discussion_r1798543848). Thus far, for better or worse, the only way I've been able to succesfully and reliably fix the AutoAWQ issues is by applying the patch proposed in https://github.com/huggingface/transformers/pull/33742.

**Comment by davedgd** [comment] 2024-10-13 20:35
Please ignore my earlier comment (I deleted it to avoid confusion) -- it turns out there are multiple issues with AutoAWQ that are complicating my testing of relevant fixes, and I need to more thoroughly evaluate what's going on to figure out the best solution(s).

**Closed** 2024-11-16 08:08 UTC
Labels: bug

**Comment by ArlanCooper** [comment] 2024-12-03 13:47
+1, qwen2.5-72b-instruct

**Comment by ArlanCooper** [comment] 2024-12-03 13:48
has solve it?

**Comment by steveepreston** [comment] 2025-01-10 17:46
Facing this issue on `transformers 4.48.0`

**Comment by ArthurZucker** [comment] 2025-01-13 08:37
Is it the same as #35505? 🤗
